-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-05-05T01:22:30.526Z

CREATE TABLE "lkp_person_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "allows_employment" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employee_event_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "event_category" varchar(30) NOT NULL,
  "is_separation" boolean NOT NULL DEFAULT false,
  "triggers_onboarding" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employment_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_w2" boolean NOT NULL DEFAULT true,
  "benefits_eligible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employment_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_payroll_active" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_full_part_time_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "min_hours_week" decimal(5,2),
  "max_hours_week" decimal(5,2),
  "benefits_eligible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_regular_temporary_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "has_end_date" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_flsa_classification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "overtime_eligible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_flsa_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "flsa_classification_id" integer,
  "overtime_eligible" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_eeo_category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "eeo1_category_num" varchar(10) NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_assignment_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_primary" boolean NOT NULL DEFAULT false,
  "allows_overlap" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_assignment_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_compensation_rate_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_annualized" boolean NOT NULL DEFAULT false,
  "unit_of_measure" varchar(30),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_compensation_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_payable" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_pay_frequency" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "periods_per_year" int NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_payroll_impact_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "affects_gross_pay" boolean NOT NULL DEFAULT true,
  "pay_percentage" decimal(5,2),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_approval_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_approved_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_leave_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "payroll_impact_type_id" integer,
  "is_accrued" boolean NOT NULL DEFAULT true,
  "is_protected" boolean NOT NULL DEFAULT false,
  "requires_documentation" boolean NOT NULL DEFAULT false,
  "max_days_per_year" int,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_leave_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_on_leave" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_document_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "requires_signature" boolean NOT NULL DEFAULT false,
  "retention_days" int,
  "is_employee_visible" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_document_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_valid" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_onboarding_plan_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_onboarding_task_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "document_type_id" integer,
  "default_due_days" int,
  "is_employee_action" boolean NOT NULL DEFAULT true,
  "is_blocking" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_onboarding_task_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_complete_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_legal_entity_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "sort_order" integer NOT NULL DEFAULT 0
);

CREATE TABLE "lkp_org_unit_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "allows_children" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_org_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_operational" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_work_location_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_on_site" boolean NOT NULL DEFAULT true,
  "requires_address" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_job_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_hirable" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_position_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_fillable" boolean NOT NULL DEFAULT true,
  "is_occupied" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "platform_audit_event" (
  "audit_event_id" uuid PRIMARY KEY NOT NULL,
  "tenant_id" uuid NOT NULL,
  "event_timestamp" timestamptz NOT NULL,
  "event_type" varchar(50) NOT NULL,
  "module_name" varchar(30),
  "entity_type" varchar(100) NOT NULL,
  "entity_id" uuid,
  "parent_entity_type" varchar(100),
  "parent_entity_id" uuid,
  "actor_user_id" uuid NOT NULL,
  "actor_display_name" varchar(200),
  "change_summary" varchar(500),
  "before_state_json" text,
  "after_state_json" text,
  "outcome" varchar(20) NOT NULL,
  "failure_reason" varchar(500),
  "ip_address" varchar(45),
  "session_id" varchar(200)
);

CREATE TABLE "person" (
  "person_id" uuid PRIMARY KEY NOT NULL,
  "person_number" varchar(50),
  "legal_first_name" varchar(100) NOT NULL,
  "legal_middle_name" varchar(100),
  "legal_last_name" varchar(100) NOT NULL,
  "name_suffix" varchar(20),
  "preferred_name" varchar(100),
  "date_of_birth" date NOT NULL,
  "national_identifier" varchar(500),
  "national_identifier_type" varchar(50),
  "gender" varchar(50),
  "pronouns" varchar(100),
  "citizenship_status" varchar(100),
  "work_authorization_status" varchar(100),
  "work_authorization_exp_date" date,
  "language_preference" varchar(20),
  "marital_status" varchar(50),
  "veteran_status" varchar(50),
  "disability_status" varchar(50),
  "person_status_id" integer NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL,
  "last_updated_by" varchar(200) NOT NULL
);

CREATE TABLE "employee_event" (
  "event_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "event_type_id" integer NOT NULL,
  "effective_date" date NOT NULL,
  "event_reason" varchar(200),
  "notes" varchar(1000),
  "initiated_by" uuid NOT NULL,
  "approved_by" uuid,
  "approval_timestamp" timestamptz,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "person_address" (
  "person_address_id" uuid PRIMARY KEY NOT NULL,
  "person_id" uuid NOT NULL,
  "address_type" varchar(50) NOT NULL,
  "address_line_1" varchar(200) NOT NULL,
  "address_line_2" varchar(200),
  "city" varchar(100) NOT NULL,
  "state_code" varchar(10) NOT NULL,
  "postal_code" varchar(20) NOT NULL,
  "country_code" varchar(5) NOT NULL,
  "phone_primary" varchar(30),
  "phone_secondary" varchar(30),
  "email_personal" varchar(200),
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "person_emergency_contact" (
  "emergency_contact_id" uuid PRIMARY KEY NOT NULL,
  "person_id" uuid NOT NULL,
  "contact_name" varchar(200) NOT NULL,
  "relationship" varchar(100),
  "phone" varchar(30),
  "email" varchar(200),
  "primary_flag" boolean NOT NULL DEFAULT false,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "org_unit" (
  "org_unit_id" uuid PRIMARY KEY NOT NULL,
  "org_unit_type_id" integer NOT NULL,
  "org_unit_code" varchar(50) NOT NULL,
  "org_unit_name" varchar(200) NOT NULL,
  "parent_org_unit_id" uuid,
  "legal_entity_id" uuid,
  "legal_entity_type_id" integer,
  "org_status_id" integer NOT NULL,
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "tax_registration_number" varchar(50),
  "country_code" varchar(5),
  "state_of_incorporation" varchar(10),
  "address_line_1" varchar(200),
  "address_line_2" varchar(200),
  "city" varchar(100),
  "state_code" varchar(10),
  "postal_code" varchar(20),
  "locality_code" varchar(50),
  "work_location_type_id" integer,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "job" (
  "job_id" uuid PRIMARY KEY NOT NULL,
  "legal_entity_id" uuid NOT NULL,
  "job_code" varchar(50) NOT NULL,
  "job_title" varchar(200) NOT NULL,
  "job_family" varchar(100),
  "job_level" varchar(50),
  "flsa_classification_id" integer NOT NULL,
  "eeo_category_id" integer NOT NULL,
  "job_status_id" integer NOT NULL,
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "position" (
  "position_id" uuid PRIMARY KEY NOT NULL,
  "job_id" uuid NOT NULL,
  "org_unit_id" uuid NOT NULL,
  "position_title" varchar(200),
  "headcount_budget" int,
  "position_status_id" integer NOT NULL,
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "employment" (
  "employment_id" uuid PRIMARY KEY NOT NULL,
  "person_id" uuid NOT NULL,
  "legal_entity_id" uuid NOT NULL,
  "employer_id" uuid NOT NULL,
  "employee_number" varchar(50) NOT NULL,
  "employment_type_id" integer NOT NULL,
  "employment_start_date" date NOT NULL,
  "employment_end_date" date,
  "original_hire_date" date,
  "termination_date" date,
  "employment_status_id" integer NOT NULL,
  "full_part_time_status_id" integer NOT NULL,
  "regular_temporary_status_id" integer NOT NULL,
  "flsa_status_id" integer NOT NULL,
  "payroll_context_id" uuid,
  "primary_work_location_id" uuid NOT NULL,
  "primary_department_id" uuid NOT NULL,
  "manager_employment_id" uuid,
  "rehire_flag" boolean NOT NULL DEFAULT false,
  "prior_employment_id" uuid,
  "primary_flag" boolean NOT NULL DEFAULT true,
  "payroll_eligibility_flag" boolean NOT NULL DEFAULT true,
  "benefits_eligibility_flag" boolean NOT NULL DEFAULT true,
  "time_tracking_required_flag" boolean NOT NULL DEFAULT false,
  "creation_timestamp" timestamptz NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL,
  "last_updated_by" varchar(200) NOT NULL
);

CREATE TABLE "assignment" (
  "assignment_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "job_id" uuid NOT NULL,
  "position_id" uuid,
  "department_id" uuid NOT NULL,
  "location_id" uuid NOT NULL,
  "payroll_context_id" uuid,
  "plan_id" uuid,
  "assignment_type_id" integer NOT NULL,
  "assignment_status_id" integer NOT NULL,
  "assignment_priority" int,
  "assignment_start_date" date NOT NULL,
  "assignment_end_date" date,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "compensation_record" (
  "compensation_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "rate_type_id" integer NOT NULL,
  "base_rate" decimal(18,4) NOT NULL,
  "rate_currency" varchar(5) NOT NULL DEFAULT 'USD',
  "annual_equivalent" decimal(18,4),
  "pay_frequency_id" integer NOT NULL,
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "compensation_status_id" integer NOT NULL,
  "change_reason_code" varchar(50) NOT NULL,
  "approval_status_id" integer NOT NULL,
  "approved_by" uuid,
  "approval_timestamp" timestamptz,
  "primary_rate_flag" boolean NOT NULL DEFAULT false,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "leave_request" (
  "leave_request_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "leave_type_id" integer NOT NULL,
  "request_date" date NOT NULL,
  "leave_start_date" date NOT NULL,
  "leave_end_date" date NOT NULL,
  "actual_return_date" date,
  "leave_status_id" integer NOT NULL,
  "leave_reason_code" varchar(50) NOT NULL,
  "payroll_impact_type_id" integer NOT NULL,
  "leave_balance_impact" decimal(10,4),
  "approved_by" uuid,
  "approval_timestamp" timestamptz,
  "hr_contact_id" uuid,
  "fmla_eligible_flag" boolean DEFAULT false,
  "notes" varchar(1000),
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "document" (
  "document_id" uuid PRIMARY KEY NOT NULL,
  "person_id" uuid NOT NULL,
  "employment_id" uuid,
  "document_type_id" integer NOT NULL,
  "document_name" varchar(200) NOT NULL,
  "document_version" int NOT NULL DEFAULT 1,
  "document_status_id" integer NOT NULL,
  "effective_date" date NOT NULL,
  "expiration_date" date,
  "storage_reference" varchar(500) NOT NULL,
  "file_format" varchar(20) NOT NULL,
  "upload_date" timestamptz NOT NULL,
  "uploaded_by" uuid NOT NULL,
  "verified_by" uuid,
  "verification_date" timestamptz,
  "superseded_by_document_id" uuid,
  "legal_hold_flag" boolean NOT NULL DEFAULT false,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "document_download_audit" (
  "audit_id" uuid PRIMARY KEY,
  "document_id" uuid NOT NULL,
  "accessed_by" uuid NOT NULL,
  "access_timestamp" timestamptz NOT NULL
);

CREATE TABLE "person_social_profile" (
  "person_id" uuid PRIMARY KEY,
  "photo_data" bytea,
  "photo_mime_type" varchar(50),
  "bio_text" varchar(1000),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "work_queue_item" (
  "work_queue_item_id" uuid PRIMARY KEY,
  "item_type" varchar(50) NOT NULL,
  "reference_id" uuid NOT NULL,
  "reference_type" varchar(50) NOT NULL,
  "employment_id" uuid,
  "assigned_role" varchar(100) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'OPEN',
  "priority" varchar(20) NOT NULL DEFAULT 'NORMAL',
  "title" varchar(200) NOT NULL,
  "description" text,
  "due_date" date,
  "created_at" timestamptz NOT NULL,
  "resolved_at" timestamptz,
  "resolved_by" uuid
);

CREATE TABLE "onboarding_plan" (
  "onboarding_plan_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "plan_template_id" uuid,
  "plan_status_id" integer NOT NULL,
  "target_start_date" date NOT NULL,
  "completion_date" date,
  "assigned_hr_contact_id" uuid,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "onboarding_task" (
  "task_id" uuid PRIMARY KEY NOT NULL,
  "onboarding_plan_id" uuid NOT NULL,
  "task_type_id" integer NOT NULL,
  "task_name" varchar(200) NOT NULL,
  "task_owner_role" varchar(100) NOT NULL,
  "task_owner_user_id" uuid,
  "due_date" date NOT NULL,
  "completion_date" date,
  "task_status_id" integer NOT NULL,
  "blocking_flag" boolean NOT NULL DEFAULT false,
  "waiver_reason" varchar(500),
  "waived_by" uuid,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "leave_balance" (
  "leave_balance_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "leave_type_id" integer NOT NULL,
  "available_balance" decimal(10,4) NOT NULL DEFAULT 0,
  "pending_balance" decimal(10,4) NOT NULL DEFAULT 0,
  "used_balance" decimal(10,4) NOT NULL DEFAULT 0,
  "entitlement_total" decimal(10,4) NOT NULL DEFAULT 0,
  "plan_year_start" date NOT NULL,
  "plan_year_end" date NOT NULL,
  "last_accrual_date" date,
  "last_updated_run_id" uuid,
  "created_timestamp" timestamptz NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "report_execution_history" (
  "execution_id" uuid PRIMARY KEY NOT NULL,
  "report_id" varchar(50) NOT NULL,
  "report_title" varchar(200) NOT NULL,
  "requested_by" uuid NOT NULL,
  "execution_status" varchar(20) NOT NULL,
  "parameters_json" text NOT NULL,
  "row_count" integer,
  "export_format" varchar(10),
  "storage_reference" varchar(500),
  "async_job_id" uuid,
  "started_at" timestamptz NOT NULL,
  "completed_at" timestamptz,
  "error_message" text,
  "created_timestamp" timestamptz NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE INDEX ON "platform_audit_event" ("tenant_id");

CREATE INDEX ON "platform_audit_event" ("event_timestamp");

CREATE INDEX ON "platform_audit_event" ("actor_user_id");

CREATE INDEX ON "platform_audit_event" ("entity_type", "entity_id");

CREATE INDEX ON "platform_audit_event" ("tenant_id", "event_timestamp");

CREATE INDEX ON "platform_audit_event" ("tenant_id", "entity_type", "entity_id");

CREATE INDEX ON "person" ("person_number");

CREATE INDEX ON "person" ("person_status_id");

CREATE INDEX ON "person" ("legal_last_name", "legal_first_name");

CREATE INDEX ON "employee_event" ("employment_id");

CREATE INDEX ON "employee_event" ("event_type_id");

CREATE INDEX ON "employee_event" ("effective_date");

CREATE INDEX ON "employee_event" ("employment_id", "effective_date");

CREATE INDEX ON "person_address" ("person_id");

CREATE INDEX ON "person_address" ("person_id", "address_type", "effective_start_date");

CREATE INDEX ON "person_emergency_contact" ("person_id");

CREATE INDEX ON "org_unit" ("org_unit_type_id");

CREATE INDEX ON "org_unit" ("org_status_id");

CREATE INDEX ON "org_unit" ("parent_org_unit_id");

CREATE INDEX ON "org_unit" ("legal_entity_id");

CREATE INDEX ON "org_unit" ("org_unit_code");

CREATE INDEX ON "job" ("legal_entity_id");

CREATE UNIQUE INDEX ON "job" ("legal_entity_id", "job_code");

CREATE INDEX ON "job" ("job_status_id");

CREATE INDEX ON "job" ("flsa_classification_id");

CREATE INDEX ON "position" ("job_id");

CREATE INDEX ON "position" ("org_unit_id");

CREATE INDEX ON "position" ("position_status_id");

CREATE INDEX ON "employment" ("person_id");

CREATE INDEX ON "employment" ("legal_entity_id");

CREATE INDEX ON "employment" ("employment_status_id");

CREATE INDEX ON "employment" ("employee_number");

CREATE INDEX ON "employment" ("manager_employment_id");

CREATE INDEX ON "employment" ("prior_employment_id");

CREATE INDEX ON "employment" ("payroll_context_id");

CREATE INDEX ON "employment" ("primary_work_location_id");

CREATE INDEX ON "employment" ("primary_department_id");

CREATE INDEX ON "assignment" ("employment_id");

CREATE INDEX ON "assignment" ("job_id");

CREATE INDEX ON "assignment" ("position_id");

CREATE INDEX ON "assignment" ("location_id");

CREATE INDEX ON "assignment" ("department_id");

CREATE INDEX ON "assignment" ("assignment_status_id");

CREATE INDEX ON "assignment" ("assignment_type_id");

CREATE INDEX ON "assignment" ("employment_id", "assignment_type_id", "assignment_start_date");

CREATE INDEX ON "compensation_record" ("employment_id");

CREATE INDEX ON "compensation_record" ("compensation_status_id");

CREATE INDEX ON "compensation_record" ("effective_start_date");

CREATE INDEX ON "compensation_record" ("employment_id", "rate_type_id", "effective_start_date");

CREATE INDEX ON "compensation_record" ("primary_rate_flag");

CREATE INDEX ON "leave_request" ("employment_id");

CREATE INDEX ON "leave_request" ("leave_status_id");

CREATE INDEX ON "leave_request" ("leave_type_id");

CREATE INDEX ON "leave_request" ("leave_start_date");

CREATE INDEX ON "leave_request" ("employment_id", "leave_start_date", "leave_end_date");

CREATE INDEX ON "document" ("person_id");

CREATE INDEX ON "document" ("employment_id");

CREATE INDEX ON "document" ("document_type_id");

CREATE INDEX ON "document" ("document_status_id");

CREATE INDEX ON "document" ("expiration_date");

CREATE INDEX ON "document" ("superseded_by_document_id");

CREATE INDEX ON "document_download_audit" ("document_id");

CREATE INDEX ON "document_download_audit" ("accessed_by");

CREATE INDEX ON "work_queue_item" ("employment_id");

CREATE INDEX ON "work_queue_item" ("reference_id");

CREATE INDEX ON "work_queue_item" ("assigned_role", "status");

CREATE INDEX ON "work_queue_item" ("status");

CREATE INDEX ON "onboarding_plan" ("employment_id");

CREATE INDEX ON "onboarding_plan" ("plan_status_id");

CREATE INDEX ON "onboarding_task" ("onboarding_plan_id");

CREATE INDEX ON "onboarding_task" ("task_status_id");

CREATE INDEX ON "onboarding_task" ("blocking_flag");

CREATE INDEX ON "onboarding_task" ("onboarding_plan_id", "blocking_flag", "task_status_id");

CREATE INDEX ON "leave_balance" ("employment_id");

CREATE INDEX ON "leave_balance" ("employment_id", "leave_type_id", "plan_year_start");

CREATE INDEX "idx_report_execution_requested_by" ON "report_execution_history" ("requested_by");

CREATE INDEX "idx_report_execution_report_date" ON "report_execution_history" ("report_id", "started_at");

CREATE INDEX "idx_report_execution_user_date" ON "report_execution_history" ("requested_by", "started_at");

CREATE INDEX "idx_report_execution_status" ON "report_execution_history" ("execution_status");

COMMENT ON TABLE "lkp_person_status" IS 'Lifecycle status of a person record';

COMMENT ON COLUMN "lkp_person_status"."id" IS 'SERIAL primary key';

COMMENT ON COLUMN "lkp_person_status"."code" IS 'e.g. ACTIVE, INACTIVE, DECEASED, RESTRICTED, ARCHIVED';

COMMENT ON COLUMN "lkp_person_status"."allows_employment" IS 'Whether this status permits active employment records';

COMMENT ON TABLE "lkp_employee_event_type" IS 'Classifies employee lifecycle events (hire, termination, transfer, etc.)';

COMMENT ON COLUMN "lkp_employee_event_type"."code" IS 'e.g. HIRE, REHIRE, TERMINATION, PROMOTION, TRANSFER, LOA_START, LOA_RETURN';

COMMENT ON COLUMN "lkp_employee_event_type"."event_category" IS 'Grouping: ONBOARDING, SEPARATION, MOVEMENT, COMPENSATION, LEAVE';

COMMENT ON COLUMN "lkp_employee_event_type"."is_separation" IS 'True if this event ends employment';

COMMENT ON COLUMN "lkp_employee_event_type"."triggers_onboarding" IS 'True if this event initiates onboarding workflow';

COMMENT ON TABLE "lkp_employment_type" IS 'Worker classification type (Employee, Contractor, Intern, etc.)';

COMMENT ON COLUMN "lkp_employment_type"."code" IS 'e.g. EMPLOYEE, CONTRACTOR, INTERN, VOLUNTEER';

COMMENT ON COLUMN "lkp_employment_type"."is_w2" IS 'W-2 tax treatment (vs 1099)';

COMMENT ON COLUMN "lkp_employment_type"."benefits_eligible" IS 'Default benefits eligibility';

COMMENT ON TABLE "lkp_employment_status" IS 'Current state of an employment record';

COMMENT ON COLUMN "lkp_employment_status"."code" IS 'e.g. ACTIVE, ON_LEAVE, SUSPENDED, TERMINATED, RETIRED';

COMMENT ON COLUMN "lkp_employment_status"."is_payroll_active" IS 'Whether employment feeds active payroll';

COMMENT ON TABLE "lkp_full_part_time_status" IS 'Full-time vs part-time classification (ACA, benefits eligibility)';

COMMENT ON COLUMN "lkp_full_part_time_status"."code" IS 'e.g. FULL_TIME, PART_TIME, PRN, ON_CALL';

COMMENT ON COLUMN "lkp_full_part_time_status"."min_hours_week" IS 'Minimum weekly hours threshold for this classification';

COMMENT ON COLUMN "lkp_full_part_time_status"."max_hours_week" IS 'Maximum weekly hours threshold';

COMMENT ON COLUMN "lkp_full_part_time_status"."benefits_eligible" IS 'ACA / plan eligibility default';

COMMENT ON TABLE "lkp_regular_temporary_status" IS 'Regular vs temporary/seasonal employment classification';

COMMENT ON COLUMN "lkp_regular_temporary_status"."code" IS 'e.g. REGULAR, TEMPORARY, SEASONAL, PROJECT_BASED';

COMMENT ON COLUMN "lkp_regular_temporary_status"."has_end_date" IS 'Whether assignments of this type require a defined end date';

COMMENT ON TABLE "lkp_flsa_classification" IS 'FLSA exemption classification (Executive, Administrative, Professional, etc.)';

COMMENT ON COLUMN "lkp_flsa_classification"."code" IS 'e.g. EXECUTIVE, ADMINISTRATIVE, PROFESSIONAL, COMPUTER, OUTSIDE_SALES, HIGHLY_COMPENSATED';

COMMENT ON COLUMN "lkp_flsa_classification"."overtime_eligible" IS 'Whether this classification is eligible for overtime';

COMMENT ON TABLE "lkp_flsa_status" IS 'FLSA exemption status assigned to a position or employee';

COMMENT ON COLUMN "lkp_flsa_status"."code" IS 'e.g. EXEMPT, NON_EXEMPT, EXEMPT_ADMIN, EXEMPT_PROF, EXEMPT_COMPUTER, EXEMPT_SALES, EXEMPT_HCE';

COMMENT ON COLUMN "lkp_flsa_status"."flsa_classification_id" IS 'FK → lkp_flsa_classification.id';

COMMENT ON COLUMN "lkp_flsa_status"."overtime_eligible" IS 'Whether OT applies';

COMMENT ON TABLE "lkp_eeo_category" IS 'EEO-1 job category for federal compliance reporting';

COMMENT ON COLUMN "lkp_eeo_category"."code" IS 'e.g. EXEC_SR_OFFICIALS, FIRST_MID_OFFICIALS, PROFESSIONALS';

COMMENT ON COLUMN "lkp_eeo_category"."eeo1_category_num" IS 'Official EEO-1 numeric category identifier';

COMMENT ON TABLE "lkp_assignment_type" IS 'Type of work assignment (Primary, Secondary, Acting, etc.)';

COMMENT ON COLUMN "lkp_assignment_type"."code" IS 'e.g. PRIMARY, SECONDARY, ADDITIONAL, ACTING, INTERIM';

COMMENT ON COLUMN "lkp_assignment_type"."is_primary" IS 'Whether this type designates the primary/home assignment';

COMMENT ON COLUMN "lkp_assignment_type"."allows_overlap" IS 'Whether multiple assignments of this type can coexist';

COMMENT ON TABLE "lkp_assignment_status" IS 'Lifecycle status of a work assignment';

COMMENT ON COLUMN "lkp_assignment_status"."code" IS 'e.g. ACTIVE, INACTIVE, PENDING, ENDED, SUSPENDED';

COMMENT ON COLUMN "lkp_assignment_status"."is_active_state" IS 'Whether this status represents an active assignment';

COMMENT ON TABLE "lkp_compensation_rate_type" IS 'How compensation is measured (salary, hourly, commission, etc.)';

COMMENT ON COLUMN "lkp_compensation_rate_type"."code" IS 'e.g. SALARY, HOURLY, DAILY, PIECE_RATE, COMMISSION, STIPEND';

COMMENT ON COLUMN "lkp_compensation_rate_type"."is_annualized" IS 'Whether the rate is expressed as an annual figure';

COMMENT ON COLUMN "lkp_compensation_rate_type"."unit_of_measure" IS 'Rate unit: YEAR, HOUR, DAY, UNIT, PERCENT, PERIOD';

COMMENT ON TABLE "lkp_compensation_status" IS 'Lifecycle status of a compensation record';

COMMENT ON COLUMN "lkp_compensation_status"."code" IS 'e.g. PROPOSED, APPROVED, ACTIVE, FROZEN, ENDED';

COMMENT ON COLUMN "lkp_compensation_status"."approval_status_id" IS 'FK → lkp_approval_status.id';

COMMENT ON COLUMN "lkp_compensation_status"."is_payable" IS 'Whether compensation is disbursable in this state';

COMMENT ON TABLE "lkp_pay_frequency" IS 'Pay cycle frequency (weekly, biweekly, semimonthly, monthly, etc.)';

COMMENT ON COLUMN "lkp_pay_frequency"."code" IS 'e.g. WEEKLY, BIWEEKLY, SEMIMONTHLY, MONTHLY, QUARTERLY, ANNUAL';

COMMENT ON COLUMN "lkp_pay_frequency"."periods_per_year" IS 'Number of pay periods per year (52, 26, 24, 12, 4, 1)';

COMMENT ON TABLE "lkp_payroll_impact_type" IS 'How an event or leave type impacts payroll (paid, unpaid, partial, etc.)';

COMMENT ON COLUMN "lkp_payroll_impact_type"."code" IS 'e.g. PAID, UNPAID, PARTIAL_PAY, REDUCED_RATE, COMPANY_FUNDED, STATE_FUNDED';

COMMENT ON COLUMN "lkp_payroll_impact_type"."affects_gross_pay" IS 'Whether this impact type modifies gross pay calculation';

COMMENT ON COLUMN "lkp_payroll_impact_type"."pay_percentage" IS 'Default pay percentage (100.00 = full pay, 0.00 = unpaid)';

COMMENT ON TABLE "lkp_approval_status" IS 'Generic approval workflow status (used across leave, comp, documents, etc.)';

COMMENT ON COLUMN "lkp_approval_status"."code" IS 'e.g. DRAFT, PENDING, APPROVED, REJECTED, CANCELLED, ESCALATED';

COMMENT ON COLUMN "lkp_approval_status"."is_approved_state" IS 'Whether this state represents approval';

COMMENT ON TABLE "lkp_leave_type" IS 'Classification of leave/absence (vacation, sick, FMLA, etc.)';

COMMENT ON COLUMN "lkp_leave_type"."code" IS 'e.g. VACATION, SICK, PERSONAL, FMLA, BEREAVEMENT, JURY_DUTY, MILITARY, PTO, STD, LTD';

COMMENT ON COLUMN "lkp_leave_type"."payroll_impact_type_id" IS 'FK → lkp_payroll_impact_type.id; default payroll treatment';

COMMENT ON COLUMN "lkp_leave_type"."is_accrued" IS 'Whether this leave type accrues a balance';

COMMENT ON COLUMN "lkp_leave_type"."is_protected" IS 'Whether legally protected (FMLA, ADA, military)';

COMMENT ON COLUMN "lkp_leave_type"."requires_documentation" IS 'Whether supporting docs are required';

COMMENT ON COLUMN "lkp_leave_type"."max_days_per_year" IS 'Statutory or policy cap, if applicable';

COMMENT ON TABLE "lkp_leave_status" IS 'Lifecycle status of a leave request';

COMMENT ON COLUMN "lkp_leave_status"."code" IS 'e.g. REQUESTED, APPROVED, IN_PROGRESS, COMPLETED, DENIED, CANCELLED';

COMMENT ON COLUMN "lkp_leave_status"."approval_status_id" IS 'FK → lkp_approval_status.id';

COMMENT ON COLUMN "lkp_leave_status"."is_on_leave" IS 'Whether this status means employee is actively on leave';

COMMENT ON TABLE "lkp_document_type" IS 'Classification of HR documents (offer letter, I-9, W-4, NDA, etc.)';

COMMENT ON COLUMN "lkp_document_type"."code" IS 'e.g. OFFER_LETTER, I9, W4, NDA, PERFORMANCE_REVIEW, POLICY_ACK, CONTRACT, CERTIFICATION, LICENSE';

COMMENT ON COLUMN "lkp_document_type"."requires_signature" IS 'Whether e-signature is required';

COMMENT ON COLUMN "lkp_document_type"."retention_days" IS 'Minimum retention period in days per policy/regulation';

COMMENT ON COLUMN "lkp_document_type"."is_employee_visible" IS 'Whether visible in employee self-service';

COMMENT ON TABLE "lkp_document_status" IS 'Lifecycle status of an HR document';

COMMENT ON COLUMN "lkp_document_status"."code" IS 'e.g. DRAFT, PENDING_SIGNATURE, SIGNED, EXPIRED, ARCHIVED, VOIDED, SUPERSEDED';

COMMENT ON COLUMN "lkp_document_status"."approval_status_id" IS 'FK → lkp_approval_status.id; mapped approval state if doc requires approval';

COMMENT ON COLUMN "lkp_document_status"."is_valid" IS 'Whether the document is considered legally valid in this state';

COMMENT ON TABLE "lkp_onboarding_plan_status" IS 'Status of an onboarding plan instance';

COMMENT ON COLUMN "lkp_onboarding_plan_status"."code" IS 'e.g. NOT_STARTED, IN_PROGRESS, BLOCKING_COMPLETE, COMPLETED, CANCELLED, ON_HOLD';

COMMENT ON TABLE "lkp_onboarding_task_type" IS 'Category of onboarding task (document, training, equipment, access, etc.)';

COMMENT ON COLUMN "lkp_onboarding_task_type"."code" IS 'e.g. DOCUMENT_SUBMISSION, TRAINING, EQUIPMENT_SETUP, SYSTEM_ACCESS, ORIENTATION, MENTOR_ASSIGNMENT, BENEFITS_ENROLLMENT, POLICY_ACK';

COMMENT ON COLUMN "lkp_onboarding_task_type"."document_type_id" IS 'FK → lkp_document_type.id; linked document type if this is a doc task';

COMMENT ON COLUMN "lkp_onboarding_task_type"."default_due_days" IS 'Default number of days after hire to complete';

COMMENT ON COLUMN "lkp_onboarding_task_type"."is_employee_action" IS 'Whether the new hire performs this task (vs HR/IT)';

COMMENT ON COLUMN "lkp_onboarding_task_type"."is_blocking" IS 'Whether this task blocks plan completion';

COMMENT ON TABLE "lkp_onboarding_task_status" IS 'Lifecycle status of an individual onboarding task';

COMMENT ON COLUMN "lkp_onboarding_task_status"."code" IS 'e.g. PENDING, IN_PROGRESS, COMPLETED, SKIPPED, OVERDUE, BLOCKED, WAIVED';

COMMENT ON COLUMN "lkp_onboarding_task_status"."approval_status_id" IS 'FK → lkp_approval_status.id; if task requires approval';

COMMENT ON COLUMN "lkp_onboarding_task_status"."is_complete_state" IS 'Whether this status counts toward plan completion';

COMMENT ON TABLE "lkp_org_unit_type" IS 'Type of organizational unit (legal entity, division, department, location, etc.)';

COMMENT ON COLUMN "lkp_org_unit_type"."code" IS 'e.g. LEGAL_ENTITY, COMPANY, DIVISION, DEPARTMENT, TEAM, COST_CENTER, BUSINESS_UNIT, LOCATION, REGION';

COMMENT ON COLUMN "lkp_org_unit_type"."allows_children" IS 'Whether this unit type can have child units';

COMMENT ON TABLE "lkp_org_status" IS 'Lifecycle status of an organizational unit';

COMMENT ON COLUMN "lkp_org_status"."code" IS 'e.g. ACTIVE, INACTIVE, PENDING_ACTIVATION, MERGED, DISSOLVED, ARCHIVED';

COMMENT ON COLUMN "lkp_org_status"."is_operational" IS 'Whether the org unit is operationally functional';

COMMENT ON TABLE "lkp_work_location_type" IS 'Classification of work locations (office, remote, hybrid, field, etc.)';

COMMENT ON COLUMN "lkp_work_location_type"."code" IS 'e.g. OFFICE, REMOTE, HYBRID, FIELD, CLIENT_SITE, WAREHOUSE';

COMMENT ON COLUMN "lkp_work_location_type"."is_on_site" IS 'Whether employees physically report to this location';

COMMENT ON COLUMN "lkp_work_location_type"."requires_address" IS 'Whether a physical address is required';

COMMENT ON TABLE "lkp_job_status" IS 'Status of a job definition/title in the catalog';

COMMENT ON COLUMN "lkp_job_status"."code" IS 'e.g. ACTIVE, FROZEN, ABOLISHED, UNDER_REVIEW, PENDING_APPROVAL, INACTIVE';

COMMENT ON COLUMN "lkp_job_status"."is_hirable" IS 'Whether positions under this job can be filled';

COMMENT ON TABLE "lkp_position_status" IS 'Status of an individual position (headcount slot)';

COMMENT ON COLUMN "lkp_position_status"."code" IS 'e.g. OPEN, FILLED, FROZEN, ABOLISHED, PENDING_BUDGET';

COMMENT ON COLUMN "lkp_position_status"."is_fillable" IS 'Whether this position can accept an incumbent';

COMMENT ON COLUMN "lkp_position_status"."is_occupied" IS 'Whether this status implies a current incumbent';

COMMENT ON COLUMN "platform_audit_event"."audit_event_id" IS 'System-generated';

COMMENT ON COLUMN "platform_audit_event"."tenant_id" IS 'Owning tenant';

COMMENT ON COLUMN "platform_audit_event"."event_timestamp" IS 'Server UTC time of the event';

COMMENT ON COLUMN "platform_audit_event"."event_type" IS 'CREATE | UPDATE | DELETE | STATUS_CHANGE | VIEW | EXPORT | LOGIN | LOGOUT | LOGIN_FAILED | ENROLL | DISENROLL';

COMMENT ON COLUMN "platform_audit_event"."module_name" IS 'HRIS | PAYROLL | BENEFITS | TIME | REPORTING | PLATFORM';

COMMENT ON COLUMN "platform_audit_event"."entity_type" IS 'PayrollRun | PayrollContext | Employment | CompensationRecord | etc.';

COMMENT ON COLUMN "platform_audit_event"."entity_id" IS 'PK of the affected record; null for login events';

COMMENT ON COLUMN "platform_audit_event"."parent_entity_type" IS 'Owning entity type, e.g. PayrollContext when entity is PayrollPeriod';

COMMENT ON COLUMN "platform_audit_event"."parent_entity_id" IS 'PK of the owning record';

COMMENT ON COLUMN "platform_audit_event"."actor_user_id" IS 'Keycloak subject claim; Guid.Empty for system jobs';

COMMENT ON COLUMN "platform_audit_event"."actor_display_name" IS 'Denormalised display name at time of event';

COMMENT ON COLUMN "platform_audit_event"."change_summary" IS 'Human-readable one-line description of what changed';

COMMENT ON COLUMN "platform_audit_event"."before_state_json" IS 'JSON snapshot of relevant fields before operation';

COMMENT ON COLUMN "platform_audit_event"."after_state_json" IS 'JSON snapshot of relevant fields after operation';

COMMENT ON COLUMN "platform_audit_event"."outcome" IS 'SUCCESS | FAILURE | PARTIAL';

COMMENT ON COLUMN "platform_audit_event"."failure_reason" IS 'Populated when outcome = FAILURE';

COMMENT ON COLUMN "platform_audit_event"."ip_address" IS 'IPv4 or IPv6 of the client connection';

COMMENT ON COLUMN "platform_audit_event"."session_id" IS 'Blazor circuit ID or HTTP session ID';

COMMENT ON COLUMN "person"."person_id" IS 'System-generated. Immutable. Enduring human identity key.';

COMMENT ON COLUMN "person"."person_number" IS 'Optional human-facing or integration-facing identifier';

COMMENT ON COLUMN "person"."national_identifier" IS 'Encrypted at rest. SSN for US. Access-controlled.';

COMMENT ON COLUMN "person"."national_identifier_type" IS 'SSN, SIN, NIN, etc.';

COMMENT ON COLUMN "person"."gender" IS 'Self-identified; controlled vocabulary';

COMMENT ON COLUMN "person"."pronouns" IS 'Self-identified';

COMMENT ON COLUMN "person"."person_status_id" IS 'FK → lkp_person_status.id';

COMMENT ON COLUMN "employee_event"."event_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "employee_event"."event_type_id" IS 'FK → lkp_employee_event_type.id';

COMMENT ON COLUMN "person_address"."address_type" IS 'PRIMARY, MAILING, PRIOR';

COMMENT ON COLUMN "person_address"."state_code" IS 'ISO 3166-2';

COMMENT ON COLUMN "person_address"."country_code" IS 'ISO 3166-1 alpha-2';

COMMENT ON COLUMN "org_unit"."org_unit_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "org_unit"."org_unit_type_id" IS 'FK → lkp_org_unit_type.id';

COMMENT ON COLUMN "org_unit"."parent_org_unit_id" IS 'Null for root nodes; must not create cycles';

COMMENT ON COLUMN "org_unit"."legal_entity_id" IS 'FK → org_unit.org_unit_id (LEGAL_ENTITY type). Self-referencing for legal entity rows. All other org unit types point to their owning entity.';

COMMENT ON COLUMN "org_unit"."legal_entity_type_id" IS 'FK → lkp_legal_entity_type.id';

COMMENT ON COLUMN "org_unit"."org_status_id" IS 'FK → lkp_org_status.id';

COMMENT ON COLUMN "org_unit"."tax_registration_number" IS 'EIN for US legal entities';

COMMENT ON COLUMN "org_unit"."country_code" IS 'ISO 3166-1 alpha-2; required for legal entities';

COMMENT ON COLUMN "org_unit"."state_code" IS 'US state code; drives tax jurisdiction';

COMMENT ON COLUMN "org_unit"."locality_code" IS 'Local tax jurisdiction code';

COMMENT ON COLUMN "org_unit"."work_location_type_id" IS 'FK → lkp_work_location_type.id';

COMMENT ON COLUMN "job"."job_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "job"."legal_entity_id" IS 'FK → org_unit.org_unit_id (LEGAL_ENTITY type). Jobs are scoped to a legal entity.';

COMMENT ON COLUMN "job"."job_code" IS 'Unique within legal_entity_id; not globally unique.';

COMMENT ON COLUMN "job"."flsa_classification_id" IS 'FK → lkp_flsa_classification.id';

COMMENT ON COLUMN "job"."eeo_category_id" IS 'FK → lkp_eeo_category.id';

COMMENT ON COLUMN "job"."job_status_id" IS 'FK → lkp_job_status.id';

COMMENT ON COLUMN "position"."position_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "position"."position_title" IS 'Override title; if null, inherits from job_title';

COMMENT ON COLUMN "position"."position_status_id" IS 'FK → lkp_position_status.id';

COMMENT ON COLUMN "employment"."employment_id" IS 'System-generated. Immutable. Payroll anchor.';

COMMENT ON COLUMN "employment"."legal_entity_id" IS 'Org unit of type LEGAL_ENTITY';

COMMENT ON COLUMN "employment"."employer_id" IS 'Same as legal_entity_id in standard deployments';

COMMENT ON COLUMN "employment"."employment_type_id" IS 'FK → lkp_employment_type.id';

COMMENT ON COLUMN "employment"."employment_status_id" IS 'FK → lkp_employment_status.id';

COMMENT ON COLUMN "employment"."full_part_time_status_id" IS 'FK → lkp_full_part_time_status.id';

COMMENT ON COLUMN "employment"."regular_temporary_status_id" IS 'FK → lkp_regular_temporary_status.id';

COMMENT ON COLUMN "employment"."flsa_status_id" IS 'FK → lkp_flsa_status.id';

COMMENT ON COLUMN "employment"."payroll_context_id" IS 'Nullable — absent in HRIS-only deployments';

COMMENT ON COLUMN "employment"."primary_work_location_id" IS 'References org_unit of type LOCATION';

COMMENT ON COLUMN "employment"."primary_department_id" IS 'References org_unit of type DEPARTMENT';

COMMENT ON COLUMN "employment"."manager_employment_id" IS 'Direct manager; self-referencing';

COMMENT ON COLUMN "employment"."prior_employment_id" IS 'Prior episode on rehire';

COMMENT ON COLUMN "employment"."primary_flag" IS 'True if primary when concurrent employments exist';

COMMENT ON COLUMN "assignment"."assignment_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "assignment"."employment_id" IS 'Payroll anchor — never person_id';

COMMENT ON COLUMN "assignment"."position_id" IS 'Null if position management not in use';

COMMENT ON COLUMN "assignment"."department_id" IS 'References org_unit';

COMMENT ON COLUMN "assignment"."location_id" IS 'References org_unit of type LOCATION; drives tax jurisdiction';

COMMENT ON COLUMN "assignment"."assignment_type_id" IS 'FK → lkp_assignment_type.id';

COMMENT ON COLUMN "assignment"."assignment_status_id" IS 'FK → lkp_assignment_status.id';

COMMENT ON COLUMN "compensation_record"."compensation_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "compensation_record"."employment_id" IS 'Payroll anchor';

COMMENT ON COLUMN "compensation_record"."rate_type_id" IS 'FK → lkp_compensation_rate_type.id';

COMMENT ON COLUMN "compensation_record"."rate_currency" IS 'ISO 4217';

COMMENT ON COLUMN "compensation_record"."annual_equivalent" IS 'System-calculated';

COMMENT ON COLUMN "compensation_record"."pay_frequency_id" IS 'FK → lkp_pay_frequency.id';

COMMENT ON COLUMN "compensation_record"."compensation_status_id" IS 'FK → lkp_compensation_status.id';

COMMENT ON COLUMN "compensation_record"."approval_status_id" IS 'FK → lkp_approval_status.id';

COMMENT ON COLUMN "leave_request"."leave_request_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "leave_request"."leave_type_id" IS 'FK → lkp_leave_type.id';

COMMENT ON COLUMN "leave_request"."leave_status_id" IS 'FK → lkp_leave_status.id';

COMMENT ON COLUMN "leave_request"."payroll_impact_type_id" IS 'FK → lkp_payroll_impact_type.id';

COMMENT ON COLUMN "leave_request"."leave_balance_impact" IS 'Hours or days deducted from balance';

COMMENT ON COLUMN "document"."document_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "document"."person_id" IS 'Always associated with a Person';

COMMENT ON COLUMN "document"."employment_id" IS 'Null for person-level documents';

COMMENT ON COLUMN "document"."document_type_id" IS 'FK → lkp_document_type.id';

COMMENT ON COLUMN "document"."document_status_id" IS 'FK → lkp_document_status.id';

COMMENT ON COLUMN "document"."storage_reference" IS 'Secure reference to stored file';

COMMENT ON COLUMN "document"."legal_hold_flag" IS 'True if document is under legal hold; prevents archival and disposal';

COMMENT ON COLUMN "document_download_audit"."document_id" IS 'FK → document.document_id';

COMMENT ON COLUMN "document_download_audit"."accessed_by" IS 'Employment or user ID of the accessor';

COMMENT ON COLUMN "onboarding_plan"."onboarding_plan_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "onboarding_plan"."plan_status_id" IS 'FK → lkp_onboarding_plan_status.id';

COMMENT ON COLUMN "onboarding_task"."task_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "onboarding_task"."task_type_id" IS 'FK → lkp_onboarding_task_type.id';

COMMENT ON COLUMN "onboarding_task"."task_status_id" IS 'FK → lkp_onboarding_task_status.id';

COMMENT ON COLUMN "leave_balance"."leave_balance_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "leave_balance"."leave_type_id" IS 'FK → lkp_leave_type.id';

COMMENT ON COLUMN "report_execution_history"."report_id" IS 'Report identifier e.g. PAY-RPT-001';

COMMENT ON COLUMN "report_execution_history"."report_title" IS 'Display title at time of execution';

COMMENT ON COLUMN "report_execution_history"."requested_by" IS 'Employment ID or user ID of requesting user';

COMMENT ON COLUMN "report_execution_history"."execution_status" IS 'RUNNING, COMPLETED, FAILED, ASYNC_PENDING';

COMMENT ON COLUMN "report_execution_history"."parameters_json" IS 'JSON serialisation of ReportParameters used for this execution';

COMMENT ON COLUMN "report_execution_history"."row_count" IS 'Null until execution completes';

COMMENT ON COLUMN "report_execution_history"."export_format" IS 'CSV, XLSX, PDF, or null for on-screen view';

COMMENT ON COLUMN "report_execution_history"."storage_reference" IS 'Non-null when export file retained in storage';

COMMENT ON COLUMN "report_execution_history"."async_job_id" IS 'Non-null when execution submitted as async job';

COMMENT ON COLUMN "report_execution_history"."completed_at" IS 'Null until execution reaches terminal state';

COMMENT ON COLUMN "report_execution_history"."error_message" IS 'Non-null on FAILED status';

ALTER TABLE "person_social_profile" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id") DEFERRABLE INITIALLY IMMEDIATE;
