-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-05-05T01:21:51.300Z

CREATE TABLE "lkp_result_class" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "sign_convention" varchar(10) NOT NULL,
  "affects_gross_pay" boolean NOT NULL DEFAULT false,
  "affects_net_pay" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_run_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "affects_accumulators" boolean NOT NULL DEFAULT true,
  "is_reportable" boolean NOT NULL DEFAULT true,
  "requires_base_run" boolean NOT NULL DEFAULT false,
  "generates_payments" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_run_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_editable" boolean NOT NULL DEFAULT false,
  "allows_calculation" boolean NOT NULL DEFAULT false,
  "allows_release" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sequence_order" int NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_result_set_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_scheduled" boolean NOT NULL DEFAULT false,
  "is_off_cycle" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_result_set_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_editable" boolean NOT NULL DEFAULT false,
  "is_released" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employee_result_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_payable" boolean NOT NULL DEFAULT false,
  "is_reversible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_item_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "is_reversible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_payment_method" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_electronic" boolean NOT NULL DEFAULT false,
  "requires_bank_info" boolean NOT NULL DEFAULT false,
  "requires_physical_delivery" boolean NOT NULL DEFAULT false,
  "supports_split_payment" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_payment_context" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_scheduled" boolean NOT NULL DEFAULT false,
  "is_off_cycle" boolean NOT NULL DEFAULT false,
  "is_final" boolean NOT NULL DEFAULT false,
  "tax_method" varchar(30),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_check_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_negotiable" boolean NOT NULL DEFAULT false,
  "is_reissuable" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_impact_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "is_reversible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_impact_source_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "result_class_id" integer,
  "is_system_generated" boolean NOT NULL DEFAULT true,
  "is_adjustable" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_posting_direction" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "multiplier" decimal(3,1),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_contribution_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_accumulator_family" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "result_class_id" integer,
  "is_tax_related" boolean NOT NULL DEFAULT false,
  "is_reportable" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_accumulator_scope_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "requires_participant" boolean NOT NULL DEFAULT false,
  "requires_employer" boolean NOT NULL DEFAULT false,
  "requires_jurisdiction" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_accumulator_balance_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_period_context" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "abbreviation" varchar(10) NOT NULL,
  "reset_frequency" varchar(20) NOT NULL,
  "reset_boundary" varchar(30),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_scope_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_retroactive" boolean NOT NULL DEFAULT false,
  "requires_date_range" boolean NOT NULL DEFAULT false,
  "affects_prior_periods" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_scope_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_runnable" boolean NOT NULL DEFAULT false,
  "is_editable" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_population_method" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_dynamic" boolean NOT NULL DEFAULT false,
  "supports_preview" boolean NOT NULL DEFAULT true,
  "supports_override" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_funding_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_complete" boolean NOT NULL DEFAULT false,
  "allows_disbursement" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_remittance_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_transmitted" boolean NOT NULL DEFAULT false,
  "is_accepted" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_disbursement_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_released" boolean NOT NULL DEFAULT false,
  "is_settled" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "payroll_context" (
  "payroll_context_id" uuid PRIMARY KEY NOT NULL,
  "payroll_context_code" varchar(50) UNIQUE NOT NULL,
  "payroll_context_name" varchar(200) NOT NULL,
  "legal_entity_id" uuid NOT NULL,
  "pay_frequency_id" integer NOT NULL,
  "compensation_rate_type_id" integer,
  "context_status" varchar(20) NOT NULL,
  "parent_payroll_context_id" uuid,
  "root_payroll_context_id" uuid,
  "context_version_number" int NOT NULL DEFAULT 1,
  "context_change_reason_code" varchar(50),
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "pay_date_convention" varchar(30),
  "pay_date_offset_days" integer NOT NULL DEFAULT 5,
  "cutoff_offset_days" integer NOT NULL DEFAULT 3,
  "extra_period_policy" varchar(20) NOT NULL DEFAULT 'EXTRA_SPECIAL',
  "three_paycheck_month_rule" varchar(10) NOT NULL DEFAULT 'PRORATE',
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_period" (
  "period_id" uuid PRIMARY KEY NOT NULL,
  "payroll_context_id" uuid NOT NULL,
  "period_year" int NOT NULL,
  "period_number" int NOT NULL,
  "period_start_date" date NOT NULL,
  "period_end_date" date NOT NULL,
  "pay_date" date NOT NULL,
  "input_cutoff_date" date NOT NULL,
  "calculation_date" date,
  "correction_window_close_date" date,
  "finalization_date" date,
  "transmission_date" date,
  "calendar_status" varchar(20) NOT NULL,
  "parent_calendar_entry_id" uuid,
  "root_calendar_entry_id" uuid,
  "calendar_version_number" int NOT NULL DEFAULT 1,
  "calendar_change_reason_code" varchar(50),
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_run" (
  "run_id" uuid PRIMARY KEY NOT NULL,
  "payroll_context_id" uuid NOT NULL,
  "period_id" uuid NOT NULL,
  "pay_date" date NOT NULL,
  "run_type_id" integer NOT NULL,
  "run_status_id" integer NOT NULL,
  "run_description" varchar(500),
  "parent_run_id" uuid,
  "related_run_group_id" uuid,
  "rule_and_config_version_ref" varchar(200),
  "temporal_override_active_flag" boolean DEFAULT false,
  "temporal_override_date" date,
  "initiated_by" uuid NOT NULL,
  "run_start_timestamp" timestamptz,
  "run_end_timestamp" timestamptz,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "run_scope" (
  "run_scope_id" uuid PRIMARY KEY NOT NULL,
  "parent_run_id" uuid NOT NULL,
  "payroll_context_id" uuid NOT NULL,
  "scope_type_id" integer NOT NULL,
  "scope_status_id" integer NOT NULL,
  "trigger_reason" varchar(500) NOT NULL,
  "population_method_id" integer NOT NULL,
  "population_definition" text NOT NULL,
  "population_count" int NOT NULL,
  "population_resolved_flag" boolean NOT NULL DEFAULT false,
  "resolution_timestamp" timestamptz,
  "exception_derived_flag" boolean DEFAULT false,
  "priority_level" varchar(50) NOT NULL,
  "adjustment_flag" boolean NOT NULL DEFAULT false,
  "execution_start_timestamp" timestamptz,
  "execution_end_timestamp" timestamptz,
  "execution_result" varchar(50),
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_run_result_set" (
  "payroll_run_result_set_id" uuid PRIMARY KEY NOT NULL,
  "payroll_run_id" uuid NOT NULL,
  "run_scope_id" uuid,
  "source_period_id" uuid NOT NULL,
  "execution_period_id" uuid NOT NULL,
  "parent_payroll_run_result_set_id" uuid,
  "root_payroll_run_result_set_id" uuid,
  "result_set_lineage_sequence" int,
  "correction_reference_id" uuid,
  "result_set_status_id" integer NOT NULL,
  "result_set_type_id" integer NOT NULL,
  "execution_start_timestamp" timestamptz,
  "execution_end_timestamp" timestamptz,
  "approval_required_flag" boolean NOT NULL DEFAULT false,
  "approved_by_user_id" uuid,
  "approval_timestamp" timestamptz,
  "finalization_timestamp" timestamptz,
  "created_timestamp" timestamptz NOT NULL,
  "updated_timestamp" timestamptz NOT NULL
);

CREATE TABLE "employee_payroll_result" (
  "employee_payroll_result_id" uuid PRIMARY KEY NOT NULL,
  "payroll_run_result_set_id" uuid NOT NULL,
  "payroll_run_id" uuid NOT NULL,
  "run_scope_id" uuid,
  "employment_id" uuid NOT NULL,
  "person_id" uuid NOT NULL,
  "payroll_context_id" uuid NOT NULL,
  "source_period_id" uuid NOT NULL,
  "execution_period_id" uuid NOT NULL,
  "parent_employee_payroll_result_id" uuid,
  "root_employee_payroll_result_id" uuid,
  "result_lineage_sequence" int,
  "correction_reference_id" uuid,
  "result_status_id" integer NOT NULL,
  "pay_period_start_date" date NOT NULL,
  "pay_period_end_date" date NOT NULL,
  "pay_date" date NOT NULL,
  "gross_pay_amount" decimal(18,4) NOT NULL,
  "total_deductions_amount" decimal(18,4) NOT NULL,
  "total_employee_tax_amount" decimal(18,4) NOT NULL,
  "total_employer_contribution_amount" decimal(18,4) NOT NULL,
  "net_pay_amount" decimal(18,4) NOT NULL,
  "created_timestamp" timestamptz NOT NULL,
  "updated_timestamp" timestamptz NOT NULL
);

CREATE TABLE "earnings_result_line" (
  "earnings_result_line_id" uuid PRIMARY KEY NOT NULL,
  "employee_payroll_result_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "earnings_code" varchar(50) NOT NULL,
  "earnings_description" varchar(200) NOT NULL,
  "quantity" decimal(18,4),
  "rate" decimal(18,4),
  "calculated_amount" decimal(18,4) NOT NULL,
  "jurisdiction_split_flag" boolean NOT NULL DEFAULT false,
  "taxable_flag" boolean NOT NULL,
  "accumulator_impact_flag" boolean NOT NULL DEFAULT false,
  "source_rule_version_id" uuid,
  "correction_flag" boolean NOT NULL DEFAULT false,
  "corrects_line_id" uuid,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "deduction_result_line" (
  "deduction_result_line_id" uuid PRIMARY KEY NOT NULL,
  "employee_payroll_result_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "deduction_code" varchar(50) NOT NULL,
  "deduction_description" varchar(200) NOT NULL,
  "calculated_amount" decimal(18,4) NOT NULL,
  "pre_tax_flag" boolean NOT NULL,
  "cash_impact_flag" boolean NOT NULL,
  "accumulator_impact_flag" boolean NOT NULL DEFAULT false,
  "source_rule_version_id" uuid,
  "correction_flag" boolean NOT NULL DEFAULT false,
  "corrects_line_id" uuid,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "tax_result_line" (
  "tax_result_line_id" uuid PRIMARY KEY NOT NULL,
  "employee_payroll_result_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "jurisdiction_id" uuid NOT NULL,
  "tax_code" varchar(50) NOT NULL,
  "tax_description" varchar(200) NOT NULL,
  "taxable_wages_amount" decimal(18,4) NOT NULL,
  "calculated_amount" decimal(18,4) NOT NULL,
  "employer_flag" boolean NOT NULL DEFAULT false,
  "accumulator_impact_flag" boolean NOT NULL DEFAULT false,
  "source_rule_version_id" uuid,
  "correction_flag" boolean NOT NULL DEFAULT false,
  "corrects_line_id" uuid,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "employer_contribution_result_line" (
  "employer_contribution_result_line_id" uuid PRIMARY KEY NOT NULL,
  "employee_payroll_result_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "contribution_code" varchar(50) NOT NULL,
  "contribution_description" varchar(200) NOT NULL,
  "calculated_amount" decimal(18,4) NOT NULL,
  "accumulator_impact_flag" boolean NOT NULL DEFAULT false,
  "source_rule_version_id" uuid,
  "correction_flag" boolean NOT NULL DEFAULT false,
  "corrects_line_id" uuid,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_check" (
  "check_id" uuid PRIMARY KEY NOT NULL,
  "check_number" varchar(50) NOT NULL,
  "payroll_run_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "pay_period_start_date" date NOT NULL,
  "pay_period_end_date" date NOT NULL,
  "check_date" date NOT NULL,
  "payment_date" date NOT NULL,
  "calendar_context_id" uuid NOT NULL,
  "payment_method_id" integer NOT NULL,
  "payment_context_id" integer NOT NULL,
  "check_status_id" integer NOT NULL,
  "gross_earnings" decimal(18,4) NOT NULL,
  "total_deductions" decimal(18,4) NOT NULL,
  "total_taxes" decimal(18,4) NOT NULL,
  "net_pay" decimal(18,4) NOT NULL,
  "employer_total_cost" decimal(18,4),
  "void_reason" varchar(500),
  "corrects_check_id" uuid,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_item" (
  "payroll_item_id" uuid PRIMARY KEY NOT NULL,
  "payroll_run_id" uuid NOT NULL,
  "payroll_check_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "period_id" uuid NOT NULL,
  "result_class_id" integer NOT NULL,
  "code_type" varchar(50) NOT NULL,
  "code" varchar(50) NOT NULL,
  "description" varchar(200) NOT NULL,
  "hours" decimal(18,4),
  "rate" decimal(18,4),
  "amount" decimal(18,4) NOT NULL,
  "taxable_flag" boolean NOT NULL,
  "cash_impact_flag" boolean NOT NULL,
  "accumulator_target" varchar(100),
  "source_rule_version_id" uuid,
  "item_status_id" integer NOT NULL,
  "correction_flag" boolean NOT NULL DEFAULT false,
  "corrects_item_id" uuid,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "accumulator_definition" (
  "accumulator_definition_id" uuid PRIMARY KEY NOT NULL,
  "accumulator_family_id" integer NOT NULL,
  "accumulator_code" varchar(50) UNIQUE NOT NULL,
  "accumulator_name" varchar(200) NOT NULL,
  "scope_type_id" integer NOT NULL,
  "period_context_id" integer NOT NULL,
  "reset_type" varchar(50) NOT NULL,
  "carry_forward_flag" boolean NOT NULL DEFAULT false,
  "reporting_flag" boolean NOT NULL DEFAULT true,
  "remittance_flag" boolean NOT NULL DEFAULT false,
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "accumulator_impact" (
  "accumulator_impact_id" uuid PRIMARY KEY NOT NULL,
  "accumulator_definition_id" uuid NOT NULL,
  "payroll_run_result_set_id" uuid,
  "employee_payroll_result_id" uuid,
  "payroll_run_id" uuid NOT NULL,
  "employment_id" uuid,
  "person_id" uuid,
  "impact_status_id" integer NOT NULL,
  "impact_source_type_id" integer NOT NULL,
  "source_object_id" uuid,
  "prior_value" decimal(18,4) NOT NULL,
  "delta_value" decimal(18,4) NOT NULL,
  "new_value" decimal(18,4) NOT NULL,
  "posting_direction_id" integer NOT NULL,
  "scope_type_id" integer NOT NULL,
  "scope_object_id" uuid,
  "jurisdiction_id" uuid,
  "rule_pack_id" uuid,
  "rule_version_id" uuid,
  "retroactive_flag" boolean NOT NULL DEFAULT false,
  "reversal_flag" boolean NOT NULL DEFAULT false,
  "correction_flag" boolean NOT NULL DEFAULT false,
  "prior_accumulator_impact_id" uuid,
  "notes" varchar(500),
  "impact_timestamp" timestamptz NOT NULL,
  "created_timestamp" timestamptz NOT NULL,
  "updated_timestamp" timestamptz NOT NULL
);

CREATE TABLE "accumulator_contribution" (
  "contribution_id" uuid PRIMARY KEY NOT NULL,
  "accumulator_id" uuid NOT NULL,
  "accumulator_impact_id" uuid NOT NULL,
  "accumulator_definition_id" uuid NOT NULL,
  "parent_contribution_id" uuid,
  "root_contribution_id" uuid,
  "contribution_lineage_sequence" int,
  "correction_reference_id" uuid,
  "source_run_id" uuid NOT NULL,
  "source_result_set_id" uuid,
  "source_employee_result_id" uuid,
  "source_period_id" uuid NOT NULL,
  "execution_period_id" uuid NOT NULL,
  "employment_id" uuid,
  "scope_type_id" integer NOT NULL,
  "scope_object_id" uuid,
  "contribution_amount" decimal(18,4) NOT NULL,
  "contribution_type_id" integer NOT NULL,
  "before_value" decimal(18,4),
  "after_value" decimal(18,4),
  "reason_code" varchar(50),
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "accumulator_balance" (
  "accumulator_id" uuid PRIMARY KEY NOT NULL,
  "accumulator_definition_id" uuid NOT NULL,
  "accumulator_family_id" integer NOT NULL,
  "scope_type_id" integer NOT NULL,
  "participant_id" uuid,
  "employer_id" uuid,
  "jurisdiction_id" uuid,
  "plan_id" uuid,
  "period_context_id" integer NOT NULL,
  "calendar_context_id" uuid NOT NULL,
  "current_value" decimal(18,4) NOT NULL,
  "balance_status_id" integer NOT NULL,
  "last_updated_run_id" uuid NOT NULL,
  "last_updated_result_set_id" uuid,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_profile" (
  "payroll_profile_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid UNIQUE NOT NULL,
  "person_id" uuid NOT NULL,
  "payroll_context_id" uuid NOT NULL,
  "enrollment_status" varchar(20) NOT NULL,
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "final_pay_flag" boolean NOT NULL DEFAULT false,
  "blocking_tasks_cleared" boolean NOT NULL DEFAULT false,
  "enrollment_source" varchar(50) NOT NULL,
  "created_by" uuid NOT NULL,
  "creation_timestamp" timestamptz NOT NULL,
  "last_updated_by" uuid NOT NULL,
  "last_update_timestamp" timestamptz NOT NULL
);

CREATE TABLE "payroll_run_exception" (
  "run_exception_id" uuid PRIMARY KEY NOT NULL,
  "run_id" uuid NOT NULL,
  "employment_id" uuid NOT NULL,
  "exception_code" varchar(50) NOT NULL,
  "exception_message" varchar(500),
  "created_timestamp" timestamptz NOT NULL
);

CREATE TABLE "funding_result_set" (
  "funding_result_set_id" uuid PRIMARY KEY NOT NULL,
  "payroll_run_result_set_id" uuid NOT NULL,
  "funding_profile_id" uuid NOT NULL,
  "funding_status_id" integer NOT NULL,
  "funding_amount" decimal(18,4) NOT NULL,
  "funding_timestamp" timestamptz,
  "created_timestamp" timestamptz NOT NULL
);

CREATE TABLE "remittance_result_set" (
  "remittance_result_set_id" uuid PRIMARY KEY NOT NULL,
  "payroll_run_result_set_id" uuid NOT NULL,
  "remittance_profile_id" uuid NOT NULL,
  "total_remittance_amount" decimal(18,4) NOT NULL,
  "remittance_status_id" integer NOT NULL,
  "transmission_timestamp" timestamptz,
  "created_timestamp" timestamptz NOT NULL
);

CREATE TABLE "disbursement_result_set" (
  "disbursement_result_set_id" uuid PRIMARY KEY NOT NULL,
  "payroll_run_result_set_id" uuid NOT NULL,
  "net_pay_disbursement_id" uuid NOT NULL,
  "disbursement_status_id" integer NOT NULL,
  "disbursement_amount" decimal(18,4) NOT NULL,
  "created_timestamp" timestamptz NOT NULL
);

CREATE TABLE "tax_jurisdiction" (
  "jurisdiction_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "jurisdiction_code" varchar(20) UNIQUE NOT NULL,
  "jurisdiction_name" varchar(100) NOT NULL,
  "country_code" char(2) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "legal_entity_jurisdiction" (
  "legal_entity_id" uuid NOT NULL,
  "jurisdiction_id" integer NOT NULL,
  PRIMARY KEY ("legal_entity_id", "jurisdiction_id")
);

CREATE TABLE "payroll_calculation_steps" (
  "step_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "jurisdiction_id" integer NOT NULL,
  "step_code" varchar(50) UNIQUE NOT NULL,
  "step_name" varchar(100) NOT NULL,
  "step_type" varchar(30) NOT NULL,
  "calculation_category" varchar(40) NOT NULL,
  "sequence_number" integer NOT NULL,
  "applies_to" varchar(10) NOT NULL,
  "reduces_income_tax_wages" boolean NOT NULL DEFAULT false,
  "reduces_fica_wages" boolean NOT NULL DEFAULT false,
  "status_code" varchar(30) NOT NULL DEFAULT 'DRAFT',
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tax_filing_status" (
  "filing_status_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "jurisdiction_id" integer NOT NULL,
  "filing_status_code" varchar(20) NOT NULL,
  "filing_status_name" varchar(50) NOT NULL
);

CREATE TABLE "tax_brackets" (
  "bracket_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "step_code" varchar(50) NOT NULL,
  "filing_status_code" varchar(20),
  "effective_from" date NOT NULL,
  "effective_to" date,
  "lower_limit" decimal(18,4) NOT NULL,
  "upper_limit" decimal(18,4),
  "rate" decimal(10,6) NOT NULL
);

CREATE TABLE "tax_flat_rates" (
  "flat_rate_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "step_code" varchar(50) NOT NULL,
  "effective_from" date NOT NULL,
  "effective_to" date,
  "rate" decimal(10,6) NOT NULL,
  "wage_base" decimal(18,4),
  "period_cap_amount" decimal(18,4),
  "annual_cap_amount" decimal(18,4),
  "depends_on_step_code" varchar(50)
);

CREATE TABLE "tax_tiered_brackets" (
  "tiered_bracket_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "step_code" varchar(50) NOT NULL,
  "effective_from" date NOT NULL,
  "effective_to" date,
  "lower_limit" decimal(18,4) NOT NULL,
  "upper_limit" decimal(18,4),
  "rate" decimal(10,6) NOT NULL,
  "period_cap_amount" decimal(18,4),
  "annual_cap_amount" decimal(18,4)
);

CREATE TABLE "tax_allowances" (
  "allowance_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "step_code" varchar(50) NOT NULL,
  "filing_status_code" varchar(20),
  "effective_from" date NOT NULL,
  "effective_to" date,
  "annual_amount" decimal(18,4) NOT NULL
);

CREATE TABLE "tax_credits" (
  "credit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "step_code" varchar(50) NOT NULL,
  "effective_from" date NOT NULL,
  "effective_to" date,
  "annual_amount" decimal(18,4) NOT NULL,
  "credit_rate" decimal(10,6) NOT NULL,
  "is_refundable" boolean NOT NULL DEFAULT false
);

CREATE TABLE "lkp_tax_form_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "employee_tax_form_submission" (
  "submission_id" uuid PRIMARY KEY NOT NULL,
  "employment_id" uuid NOT NULL,
  "jurisdiction_id" integer NOT NULL,
  "form_type_id" integer NOT NULL,
  "source_document_id" uuid,
  "submitted_date" date NOT NULL,
  "exempt_flag" boolean NOT NULL DEFAULT false,
  "effective_from" date NOT NULL,
  "effective_to" date,
  "created_by" varchar(100) NOT NULL,
  "creation_timestamp" timestamptz NOT NULL
);

CREATE TABLE "employee_tax_form_detail" (
  "submission_id" uuid PRIMARY KEY NOT NULL,
  "filing_status_code" varchar(20),
  "allowance_count" integer NOT NULL DEFAULT 0,
  "additional_withholding" decimal(18,4) NOT NULL DEFAULT 0,
  "is_legacy_form" boolean NOT NULL DEFAULT false,
  "other_income_amount" decimal(18,4) NOT NULL DEFAULT 0,
  "deductions_amount" decimal(18,4) NOT NULL DEFAULT 0,
  "credits_amount" decimal(18,4) NOT NULL DEFAULT 0,
  "claim_code" smallint,
  "total_claim_amount" decimal(18,4),
  "additional_tax_amount" decimal(18,4) NOT NULL DEFAULT 0
);

CREATE TABLE "form_field_definition" (
  "field_definition_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "form_type_code" varchar(20) NOT NULL,
  "effective_from" date NOT NULL,
  "effective_to" date,
  "field_key" varchar(80) NOT NULL,
  "display_label" varchar(200) NOT NULL,
  "field_type" varchar(40) NOT NULL,
  "section_key" varchar(80),
  "section_label" varchar(160),
  "display_order" integer NOT NULL,
  "is_required" boolean NOT NULL DEFAULT false,
  "detail_column_name" varchar(80),
  "promotes_to_column" varchar(80),
  "validation_rules_json" text,
  "visibility_rule_json" text,
  "enum_values_json" text,
  "default_value_text" varchar(200),
  "help_text" text,
  "status_code" varchar(30) NOT NULL DEFAULT 'DRAFT',
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "configuration_audit_log" (
  "audit_log_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "entity_name" varchar(80) NOT NULL,
  "entity_id_text" varchar(200) NOT NULL,
  "action_code" varchar(40) NOT NULL,
  "prior_status_code" varchar(30),
  "new_status_code" varchar(30),
  "changed_by" varchar(100) NOT NULL,
  "changed_at" timestamp NOT NULL,
  "approval_note" text,
  "snapshot_json" text
);

CREATE TABLE "deduction" (
  "deduction_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "code" varchar(30) UNIQUE NOT NULL,
  "description" varchar(200) NOT NULL,
  "tax_treatment" varchar(10) NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'ACTIVE',
  "calculation_mode" varchar(20) NOT NULL DEFAULT 'FIXED_PER_PERIOD',
  "wage_base" varchar(20),
  "age_as_of_rule" varchar(10),
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "deduction_rate_table" (
  "rate_table_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "deduction_id" uuid NOT NULL,
  "rate_type" varchar(20) NOT NULL,
  "effective_from" date NOT NULL,
  "effective_to" date,
  "description" varchar(200),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "deduction_rate_entry" (
  "rate_entry_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "rate_table_id" uuid NOT NULL,
  "tier_code" varchar(20),
  "band_min" decimal(12,4),
  "band_max" decimal(12,4),
  "employee_rate" decimal(12,6) NOT NULL,
  "employer_rate" decimal(12,6)
);

CREATE TABLE "deduction_employer_match" (
  "match_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "deduction_id" uuid NOT NULL,
  "employee_group_id" uuid,
  "match_rate" decimal(8,6) NOT NULL,
  "match_cap_pct_of_gross" decimal(8,6),
  "match_cap_annual_amount" decimal(12,4),
  "match_type" varchar(20) NOT NULL DEFAULT 'PER_PERIOD',
  "effective_from" date NOT NULL,
  "effective_to" date,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "benefit_deduction_election" (
  "election_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "employment_id" uuid NOT NULL,
  "deduction_id" uuid NOT NULL,
  "tax_treatment" varchar(10) NOT NULL,
  "employee_amount" decimal(12,4) NOT NULL DEFAULT 0,
  "employer_contribution_amount" decimal(12,4),
  "contribution_pct" decimal(8,6),
  "coverage_tier" varchar(20),
  "annual_coverage_amount" decimal(12,4),
  "annual_election_amount" decimal(12,4),
  "monthly_election_amount" decimal(12,4),
  "partial_period_rule" varchar(20) NOT NULL DEFAULT 'PRORATE_DAYS',
  "effective_start_date" date NOT NULL,
  "effective_end_date" date,
  "status" varchar(20) NOT NULL,
  "source" varchar(10) NOT NULL,
  "created_by" varchar(200) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "election_version_id" uuid NOT NULL DEFAULT (gen_random_uuid()),
  "original_election_id" uuid,
  "parent_election_id" uuid,
  "correction_type" varchar(30),
  "source_event_id" uuid
);

CREATE TABLE "benefit_configuration_audit_log" (
  "log_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entity_type" varchar(100) NOT NULL,
  "entity_id" uuid NOT NULL,
  "action" varchar(30) NOT NULL,
  "changed_by" varchar(200) NOT NULL,
  "changed_at" timestamptz NOT NULL DEFAULT (now()),
  "before_value" text,
  "after_value" text
);

CREATE INDEX ON "payroll_context" ("legal_entity_id");

CREATE INDEX ON "payroll_context" ("pay_frequency_id");

CREATE INDEX ON "payroll_context" ("context_status");

CREATE INDEX ON "payroll_context" ("payroll_context_code");

CREATE INDEX ON "payroll_context" ("parent_payroll_context_id");

CREATE INDEX ON "payroll_context" ("legal_entity_id", "context_status");

CREATE INDEX ON "payroll_period" ("payroll_context_id");

CREATE INDEX ON "payroll_period" ("period_year");

CREATE INDEX ON "payroll_period" ("calendar_status");

CREATE INDEX ON "payroll_period" ("pay_date");

CREATE UNIQUE INDEX ON "payroll_period" ("payroll_context_id", "period_year", "period_number");

CREATE INDEX ON "payroll_period" ("parent_calendar_entry_id");

CREATE INDEX ON "payroll_run" ("payroll_context_id");

CREATE INDEX ON "payroll_run" ("period_id");

CREATE INDEX ON "payroll_run" ("run_status_id");

CREATE INDEX ON "payroll_run" ("parent_run_id");

CREATE INDEX ON "payroll_run" ("payroll_context_id", "period_id", "run_type_id");

CREATE INDEX ON "run_scope" ("parent_run_id");

CREATE INDEX ON "run_scope" ("scope_status_id");

CREATE INDEX ON "run_scope" ("scope_type_id");

CREATE INDEX ON "run_scope" ("payroll_context_id");

CREATE INDEX ON "payroll_run_result_set" ("payroll_run_id");

CREATE INDEX ON "payroll_run_result_set" ("run_scope_id");

CREATE INDEX ON "payroll_run_result_set" ("result_set_status_id");

CREATE INDEX ON "payroll_run_result_set" ("source_period_id");

CREATE INDEX ON "payroll_run_result_set" ("parent_payroll_run_result_set_id");

CREATE INDEX ON "payroll_run_result_set" ("root_payroll_run_result_set_id");

CREATE INDEX ON "employee_payroll_result" ("payroll_run_result_set_id");

CREATE INDEX ON "employee_payroll_result" ("payroll_run_id");

CREATE INDEX ON "employee_payroll_result" ("employment_id");

CREATE INDEX ON "employee_payroll_result" ("person_id");

CREATE INDEX ON "employee_payroll_result" ("result_status_id");

CREATE INDEX ON "employee_payroll_result" ("source_period_id");

CREATE INDEX ON "employee_payroll_result" ("parent_employee_payroll_result_id");

CREATE INDEX ON "employee_payroll_result" ("root_employee_payroll_result_id");

CREATE INDEX ON "earnings_result_line" ("employee_payroll_result_id");

CREATE INDEX ON "earnings_result_line" ("employment_id");

CREATE INDEX ON "earnings_result_line" ("earnings_code");

CREATE INDEX ON "deduction_result_line" ("employee_payroll_result_id");

CREATE INDEX ON "deduction_result_line" ("employment_id");

CREATE INDEX ON "deduction_result_line" ("deduction_code");

CREATE INDEX ON "tax_result_line" ("employee_payroll_result_id");

CREATE INDEX ON "tax_result_line" ("employment_id");

CREATE INDEX ON "tax_result_line" ("jurisdiction_id");

CREATE INDEX ON "tax_result_line" ("tax_code");

CREATE INDEX ON "employer_contribution_result_line" ("employee_payroll_result_id");

CREATE INDEX ON "employer_contribution_result_line" ("employment_id");

CREATE INDEX ON "employer_contribution_result_line" ("contribution_code");

CREATE INDEX ON "payroll_check" ("payroll_run_id");

CREATE INDEX ON "payroll_check" ("employment_id");

CREATE INDEX ON "payroll_check" ("check_status_id");

CREATE INDEX ON "payroll_check" ("check_number");

CREATE INDEX ON "payroll_check" ("corrects_check_id");

CREATE INDEX ON "payroll_item" ("payroll_run_id");

CREATE INDEX ON "payroll_item" ("payroll_check_id");

CREATE INDEX ON "payroll_item" ("employment_id");

CREATE INDEX ON "payroll_item" ("period_id");

CREATE INDEX ON "payroll_item" ("result_class_id");

CREATE INDEX ON "payroll_item" ("code");

CREATE INDEX ON "payroll_item" ("corrects_item_id");

CREATE INDEX ON "accumulator_definition" ("accumulator_code");

CREATE INDEX ON "accumulator_definition" ("accumulator_family_id");

CREATE INDEX ON "accumulator_definition" ("scope_type_id");

CREATE INDEX ON "accumulator_impact" ("accumulator_definition_id");

CREATE INDEX ON "accumulator_impact" ("payroll_run_id");

CREATE INDEX ON "accumulator_impact" ("payroll_run_result_set_id");

CREATE INDEX ON "accumulator_impact" ("employee_payroll_result_id");

CREATE INDEX ON "accumulator_impact" ("employment_id");

CREATE INDEX ON "accumulator_impact" ("impact_status_id");

CREATE INDEX ON "accumulator_impact" ("prior_accumulator_impact_id");

CREATE INDEX ON "accumulator_contribution" ("accumulator_id");

CREATE INDEX ON "accumulator_contribution" ("accumulator_impact_id");

CREATE INDEX ON "accumulator_contribution" ("accumulator_definition_id");

CREATE INDEX ON "accumulator_contribution" ("source_run_id");

CREATE INDEX ON "accumulator_contribution" ("source_period_id");

CREATE INDEX ON "accumulator_contribution" ("employment_id");

CREATE INDEX ON "accumulator_contribution" ("parent_contribution_id");

CREATE INDEX ON "accumulator_contribution" ("root_contribution_id");

CREATE INDEX ON "accumulator_balance" ("accumulator_definition_id");

CREATE INDEX ON "accumulator_balance" ("scope_type_id", "participant_id", "period_context_id", "calendar_context_id");

CREATE INDEX ON "accumulator_balance" ("accumulator_family_id", "scope_type_id", "participant_id");

CREATE INDEX ON "accumulator_balance" ("last_updated_run_id");

CREATE INDEX ON "accumulator_balance" ("balance_status_id");

CREATE UNIQUE INDEX ON "payroll_profile" ("employment_id");

CREATE INDEX ON "payroll_profile" ("payroll_context_id");

CREATE INDEX ON "payroll_profile" ("enrollment_status");

CREATE INDEX ON "payroll_profile" ("payroll_context_id", "enrollment_status");

CREATE INDEX ON "payroll_run_exception" ("run_id");

CREATE INDEX ON "payroll_run_exception" ("run_id", "employment_id");

CREATE INDEX ON "payroll_run_exception" ("exception_code");

CREATE INDEX ON "funding_result_set" ("payroll_run_result_set_id");

CREATE INDEX ON "funding_result_set" ("funding_status_id");

CREATE INDEX ON "remittance_result_set" ("payroll_run_result_set_id");

CREATE INDEX ON "remittance_result_set" ("remittance_status_id");

CREATE INDEX ON "disbursement_result_set" ("payroll_run_result_set_id");

CREATE INDEX ON "disbursement_result_set" ("disbursement_status_id");

CREATE UNIQUE INDEX ON "tax_jurisdiction" ("jurisdiction_code");

CREATE INDEX ON "tax_jurisdiction" ("country_code");

CREATE INDEX ON "tax_jurisdiction" ("is_active");

CREATE INDEX ON "legal_entity_jurisdiction" ("legal_entity_id");

CREATE INDEX ON "legal_entity_jurisdiction" ("jurisdiction_id");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id");

CREATE UNIQUE INDEX ON "payroll_calculation_steps" ("step_code");

CREATE INDEX ON "payroll_calculation_steps" ("step_type");

CREATE INDEX ON "payroll_calculation_steps" ("calculation_category");

CREATE INDEX ON "payroll_calculation_steps" ("status_code");

CREATE INDEX ON "payroll_calculation_steps" ("is_active");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id", "sequence_number");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id", "is_active");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id", "status_code");

CREATE INDEX ON "tax_filing_status" ("jurisdiction_id");

CREATE UNIQUE INDEX ON "tax_filing_status" ("jurisdiction_id", "filing_status_code");

CREATE INDEX ON "tax_brackets" ("step_code");

CREATE INDEX ON "tax_brackets" ("step_code", "filing_status_code", "effective_from");

CREATE INDEX ON "tax_brackets" ("effective_from");

CREATE INDEX ON "tax_flat_rates" ("step_code");

CREATE INDEX ON "tax_flat_rates" ("step_code", "effective_from");

CREATE INDEX ON "tax_flat_rates" ("effective_from");

CREATE INDEX ON "tax_tiered_brackets" ("step_code");

CREATE INDEX ON "tax_tiered_brackets" ("step_code", "effective_from");

CREATE INDEX ON "tax_tiered_brackets" ("effective_from");

CREATE INDEX ON "tax_allowances" ("step_code");

CREATE INDEX ON "tax_allowances" ("step_code", "filing_status_code", "effective_from");

CREATE INDEX ON "tax_allowances" ("effective_from");

CREATE INDEX ON "tax_credits" ("step_code");

CREATE INDEX ON "tax_credits" ("step_code", "effective_from");

CREATE INDEX ON "tax_credits" ("effective_from");

CREATE UNIQUE INDEX ON "lkp_tax_form_type" ("code");

CREATE INDEX ON "employee_tax_form_submission" ("employment_id");

CREATE INDEX ON "employee_tax_form_submission" ("jurisdiction_id");

CREATE INDEX ON "employee_tax_form_submission" ("form_type_id");

CREATE INDEX ON "employee_tax_form_submission" ("effective_from");

CREATE INDEX ON "employee_tax_form_submission" ("employment_id", "jurisdiction_id", "effective_from");

CREATE INDEX ON "employee_tax_form_submission" ("employment_id", "jurisdiction_id", "effective_to");

CREATE INDEX ON "form_field_definition" ("form_type_code");

CREATE UNIQUE INDEX ON "form_field_definition" ("form_type_code", "field_key", "effective_from");

CREATE INDEX ON "form_field_definition" ("effective_from");

CREATE INDEX ON "form_field_definition" ("status_code");

CREATE INDEX ON "form_field_definition" ("is_active");

CREATE INDEX ON "configuration_audit_log" ("entity_name");

CREATE INDEX ON "configuration_audit_log" ("entity_name", "entity_id_text");

CREATE INDEX ON "configuration_audit_log" ("changed_at");

CREATE INDEX ON "configuration_audit_log" ("action_code");

CREATE INDEX ON "deduction_rate_table" ("deduction_id");

CREATE INDEX ON "deduction_rate_entry" ("rate_table_id");

CREATE INDEX ON "deduction_employer_match" ("deduction_id");

CREATE INDEX ON "benefit_deduction_election" ("employment_id");

CREATE INDEX ON "benefit_deduction_election" ("deduction_id");

CREATE INDEX ON "benefit_deduction_election" ("status");

CREATE INDEX ON "benefit_deduction_election" ("effective_start_date", "effective_end_date");

COMMENT ON TABLE "lkp_result_class" IS 'Top-level classification of payroll result lines (Earning, Deduction, Tax, Employer Contribution)';

COMMENT ON COLUMN "lkp_result_class"."code" IS 'e.g. EARNING, DEDUCTION, TAX, EMPLOYER_CONTRIBUTION';

COMMENT ON COLUMN "lkp_result_class"."sign_convention" IS 'POSITIVE (adds to gross) or NEGATIVE (subtracts from gross)';

COMMENT ON COLUMN "lkp_result_class"."affects_gross_pay" IS 'Whether this class factors into gross pay calculation';

COMMENT ON COLUMN "lkp_result_class"."affects_net_pay" IS 'Whether this class factors into net pay calculation';

COMMENT ON TABLE "lkp_run_type" IS 'Classification of payroll run types (regular, adjustment, correction, etc.)';

COMMENT ON COLUMN "lkp_run_type"."code" IS 'e.g. REGULAR, ADJUSTMENT, CORRECTION, REPROCESSING, SUPPLEMENTAL, SIMULATION';

COMMENT ON COLUMN "lkp_run_type"."affects_accumulators" IS 'Whether this run type updates accumulator balances';

COMMENT ON COLUMN "lkp_run_type"."is_reportable" IS 'Whether included in standard payroll reports and filings';

COMMENT ON COLUMN "lkp_run_type"."requires_base_run" IS 'Whether this type requires a reference to an original/base run';

COMMENT ON COLUMN "lkp_run_type"."generates_payments" IS 'Whether this run type produces disbursable payments';

COMMENT ON TABLE "lkp_run_status" IS 'Lifecycle status of a payroll run — governs what operations are permitted at each stage';

COMMENT ON COLUMN "lkp_run_status"."code" IS 'e.g. DRAFT, OPEN, CALCULATING, CALCULATED, UNDER_REVIEW, APPROVED, RELEASING, RELEASED, CLOSED, FAILED, CANCELLED';

COMMENT ON COLUMN "lkp_run_status"."is_editable" IS 'Whether payroll inputs can be modified in this state';

COMMENT ON COLUMN "lkp_run_status"."allows_calculation" IS 'Whether the calculation engine can execute';

COMMENT ON COLUMN "lkp_run_status"."allows_release" IS 'Whether payments can be released in this state';

COMMENT ON COLUMN "lkp_run_status"."is_error_state" IS 'Whether this state indicates a processing failure';

COMMENT ON COLUMN "lkp_run_status"."sequence_order" IS 'Expected progression order (1 = first state)';

COMMENT ON TABLE "lkp_result_set_type" IS 'Classification of result set origin (regular run, off-cycle, adjustment, correction)';

COMMENT ON COLUMN "lkp_result_set_type"."code" IS 'e.g. REGULAR_RUN, OFF_CYCLE, ADJUSTMENT_RUN, CORRECTION_RUN';

COMMENT ON COLUMN "lkp_result_set_type"."is_scheduled" IS 'Whether this type runs on a regular calendar schedule';

COMMENT ON COLUMN "lkp_result_set_type"."is_off_cycle" IS 'Whether this type represents an off-cycle / ad-hoc result set';

COMMENT ON TABLE "lkp_result_set_status" IS 'Lifecycle status of a payroll result set';

COMMENT ON COLUMN "lkp_result_set_status"."code" IS 'e.g. PENDING, CALCULATED, APPROVED, RELEASED, FINALIZED, ARCHIVED';

COMMENT ON COLUMN "lkp_result_set_status"."is_editable" IS 'Whether result set data can be modified';

COMMENT ON COLUMN "lkp_result_set_status"."is_released" IS 'Whether funds have been released for this result set';

COMMENT ON TABLE "lkp_employee_result_status" IS 'Lifecycle status of an individual employee payroll result';

COMMENT ON COLUMN "lkp_employee_result_status"."code" IS 'e.g. CALCULATED, APPROVED, RELEASED, FINALIZED, CORRECTED, REVERSED';

COMMENT ON COLUMN "lkp_employee_result_status"."is_payable" IS 'Whether payment can be issued in this state';

COMMENT ON COLUMN "lkp_employee_result_status"."is_reversible" IS 'Whether the result can be reversed from this state';

COMMENT ON TABLE "lkp_item_status" IS 'Status of a payroll line item (earning line, deduction line, tax line)';

COMMENT ON COLUMN "lkp_item_status"."code" IS 'e.g. DRAFT, POSTED, VOIDED, CORRECTED';

COMMENT ON COLUMN "lkp_item_status"."is_active_state" IS 'Whether the item is currently in effect';

COMMENT ON COLUMN "lkp_item_status"."is_reversible" IS 'Whether the item can be voided or corrected from this state';

COMMENT ON TABLE "lkp_payment_method" IS 'How payment is delivered to the employee (direct deposit, check, paycard, etc.)';

COMMENT ON COLUMN "lkp_payment_method"."code" IS 'e.g. DIRECT_DEPOSIT, PRINTED_CHECK, PAYCARD, CASH, MANUAL_CHECK, OTHER';

COMMENT ON COLUMN "lkp_payment_method"."is_electronic" IS 'Whether payment is transmitted electronically (ACH, wire, paycard)';

COMMENT ON COLUMN "lkp_payment_method"."requires_bank_info" IS 'Whether employee bank/routing info is required';

COMMENT ON COLUMN "lkp_payment_method"."requires_physical_delivery" IS 'Whether a physical instrument must be delivered';

COMMENT ON COLUMN "lkp_payment_method"."supports_split_payment" IS 'Whether this method supports split/partial allocation';

COMMENT ON TABLE "lkp_payment_context" IS 'Context in which a payment is issued — affects tax withholding method and reporting';

COMMENT ON COLUMN "lkp_payment_context"."code" IS 'e.g. REGULAR, SUPPLEMENTAL, CORRECTION, FINAL_PAY, OFF_CYCLE';

COMMENT ON COLUMN "lkp_payment_context"."is_scheduled" IS 'Whether this context occurs on the regular pay calendar';

COMMENT ON COLUMN "lkp_payment_context"."is_off_cycle" IS 'Whether this is an off-cycle payment';

COMMENT ON COLUMN "lkp_payment_context"."is_final" IS 'Whether this context represents final/separation pay';

COMMENT ON COLUMN "lkp_payment_context"."tax_method" IS 'Default tax calculation method: AGGREGATE, FLAT_RATE, SUPPLEMENTAL_RATE';

COMMENT ON TABLE "lkp_check_status" IS 'Lifecycle status of a payroll check or payment instrument';

COMMENT ON COLUMN "lkp_check_status"."code" IS 'e.g. DRAFT, GENERATED, RELEASED, VOIDED, REPLACED, RETURNED';

COMMENT ON COLUMN "lkp_check_status"."is_negotiable" IS 'Whether the check can be cashed/deposited in this state';

COMMENT ON COLUMN "lkp_check_status"."is_reissuable" IS 'Whether a replacement can be issued from this state';

COMMENT ON TABLE "lkp_impact_status" IS 'Status of a payroll impact record';

COMMENT ON COLUMN "lkp_impact_status"."code" IS 'e.g. CALCULATED, POSTED, REVERSED, CORRECTED, SUPERSEDED';

COMMENT ON COLUMN "lkp_impact_status"."is_active_state" IS 'Whether the impact is currently reflected in balances';

COMMENT ON COLUMN "lkp_impact_status"."is_reversible" IS 'Whether the impact can be reversed from this state';

COMMENT ON TABLE "lkp_impact_source_type" IS 'Identifies where a payroll impact originated (earnings line, deduction line, tax line, etc.)';

COMMENT ON COLUMN "lkp_impact_source_type"."code" IS 'e.g. EARNINGS_LINE, DEDUCTION_LINE, TAX_LINE, EMPLOYER_CONTRIBUTION_LINE, CORRECTION_LINE, MANUAL_ADJUSTMENT, OTHER';

COMMENT ON COLUMN "lkp_impact_source_type"."result_class_id" IS 'FK → lkp_result_class.id; NULL for CORRECTION_LINE, MANUAL_ADJUSTMENT, OTHER';

COMMENT ON COLUMN "lkp_impact_source_type"."is_system_generated" IS 'Whether this source type is created by the calc engine vs manual entry';

COMMENT ON COLUMN "lkp_impact_source_type"."is_adjustable" IS 'Whether manual adjustments are allowed for this source type';

COMMENT ON TABLE "lkp_posting_direction" IS 'Direction of a posting or accumulator contribution (increase, decrease, neutral, derived)';

COMMENT ON COLUMN "lkp_posting_direction"."code" IS 'e.g. INCREASE, DECREASE, NEUTRAL, DERIVED';

COMMENT ON COLUMN "lkp_posting_direction"."multiplier" IS '+1.0 (INCREASE), -1.0 (DECREASE), 0.0 (NEUTRAL), NULL (DERIVED — computed at runtime)';

COMMENT ON TABLE "lkp_contribution_type" IS 'Nature of an accumulator contribution (standard posting, reversal, correction, reset)';

COMMENT ON COLUMN "lkp_contribution_type"."code" IS 'e.g. STANDARD, REVERSAL, CORRECTION, RESET';

COMMENT ON TABLE "lkp_accumulator_family" IS 'Functional grouping of accumulators (gross wages, deductions, taxes, etc.)';

COMMENT ON COLUMN "lkp_accumulator_family"."code" IS 'e.g. GROSS_WAGES, PRE_TAX_DEDUCTIONS, FEDERAL_TAX_WITHHELD, SOCIAL_SECURITY, MEDICARE, RETIREMENT';

COMMENT ON COLUMN "lkp_accumulator_family"."result_class_id" IS 'FK → lkp_result_class.id; primary result class for this family';

COMMENT ON COLUMN "lkp_accumulator_family"."is_tax_related" IS 'Whether this family relates to tax accumulators';

COMMENT ON COLUMN "lkp_accumulator_family"."is_reportable" IS 'Whether included in standard year-end reporting';

COMMENT ON TABLE "lkp_accumulator_scope_type" IS 'Dimensional scope of an accumulator (employee-level, employer-level, jurisdiction-level)';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."code" IS 'e.g. EMPLOYEE, EMPLOYER, EMPLOYEE_JURISDICTION, EMPLOYER_JURISDICTION, CLIENT_JURISDICTION';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."requires_participant" IS 'Whether a participant (employee) ID is required';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."requires_employer" IS 'Whether an employer ID is required';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."requires_jurisdiction" IS 'Whether a jurisdiction ID is required';

COMMENT ON TABLE "lkp_accumulator_balance_status" IS 'Status of an accumulator balance snapshot (active, reset at period boundary, archived)';

COMMENT ON COLUMN "lkp_accumulator_balance_status"."code" IS 'e.g. ACTIVE, RESET, ARCHIVED';

COMMENT ON COLUMN "lkp_accumulator_balance_status"."is_active_state" IS 'Whether the balance is currently in use';

COMMENT ON TABLE "lkp_period_context" IS 'Time window for accumulator balances — period-to-date, quarter-to-date, year-to-date, lifetime';

COMMENT ON COLUMN "lkp_period_context"."code" IS 'e.g. PTD, QTD, YTD, PLAN_YEAR, LTD';

COMMENT ON COLUMN "lkp_period_context"."abbreviation" IS 'Short display code: PTD, QTD, YTD, PY, LTD';

COMMENT ON COLUMN "lkp_period_context"."reset_frequency" IS 'When the accumulator resets: PER_PAY, QUARTERLY, ANNUALLY, PLAN_YEAR, NEVER';

COMMENT ON COLUMN "lkp_period_context"."reset_boundary" IS 'Boundary event: PAY_PERIOD_END, QUARTER_END, YEAR_END, PLAN_YEAR_END, NULL';

COMMENT ON TABLE "lkp_scope_type" IS 'Scope of a payroll calculation — full run, catch-up, retroactive, recovery';

COMMENT ON COLUMN "lkp_scope_type"."code" IS 'e.g. FULL, CATCH_UP, RETRO, RECOVERY';

COMMENT ON COLUMN "lkp_scope_type"."is_retroactive" IS 'Whether this scope reaches back to prior periods';

COMMENT ON COLUMN "lkp_scope_type"."requires_date_range" IS 'Whether a lookback date range is required';

COMMENT ON COLUMN "lkp_scope_type"."affects_prior_periods" IS 'Whether accumulator adjustments are applied to prior periods';

COMMENT ON TABLE "lkp_scope_status" IS 'Lifecycle status of a processing scope or batch';

COMMENT ON COLUMN "lkp_scope_status"."code" IS 'e.g. DRAFT, VALIDATED, READY, RUNNING, COMPLETED, FAILED, CANCELLED';

COMMENT ON COLUMN "lkp_scope_status"."is_runnable" IS 'Whether the scope/batch can be submitted for processing';

COMMENT ON COLUMN "lkp_scope_status"."is_editable" IS 'Whether scope parameters can be modified';

COMMENT ON COLUMN "lkp_scope_status"."is_error_state" IS 'Whether this state indicates a processing failure';

COMMENT ON TABLE "lkp_population_method" IS 'How the employee population for a payroll run is determined (explicit list, dynamic query, exception-based)';

COMMENT ON COLUMN "lkp_population_method"."code" IS 'e.g. EXPLICIT, QUERY, EXCEPTION';

COMMENT ON COLUMN "lkp_population_method"."is_dynamic" IS 'Whether population is evaluated at runtime (QUERY) vs fixed at setup (EXPLICIT)';

COMMENT ON COLUMN "lkp_population_method"."supports_preview" IS 'Whether the resolved population can be previewed before run';

COMMENT ON COLUMN "lkp_population_method"."supports_override" IS 'Whether individual members can be added/removed after resolution';

COMMENT ON TABLE "lkp_funding_status" IS 'Whether payroll funding (employer bank draw) succeeded, partially succeeded, or failed';

COMMENT ON COLUMN "lkp_funding_status"."code" IS 'e.g. FUNDED, PARTIALLY_FUNDED, FAILED';

COMMENT ON COLUMN "lkp_funding_status"."is_complete" IS 'Whether funding is fully satisfied';

COMMENT ON COLUMN "lkp_funding_status"."allows_disbursement" IS 'Whether disbursement can proceed in this state';

COMMENT ON COLUMN "lkp_funding_status"."is_error_state" IS 'Whether this state indicates a funding failure';

COMMENT ON TABLE "lkp_remittance_status" IS 'Status of a tax or benefit remittance to an agency or vendor';

COMMENT ON COLUMN "lkp_remittance_status"."code" IS 'e.g. PREPARED, RELEASED, TRANSMITTED, ACCEPTED, REJECTED';

COMMENT ON COLUMN "lkp_remittance_status"."is_transmitted" IS 'Whether the remittance has been sent to the receiving party';

COMMENT ON COLUMN "lkp_remittance_status"."is_accepted" IS 'Whether the receiving party has acknowledged receipt';

COMMENT ON COLUMN "lkp_remittance_status"."is_error_state" IS 'Whether this state indicates a remittance failure';

COMMENT ON TABLE "lkp_disbursement_status" IS 'Status of an employee payment disbursement through the banking settlement lifecycle';

COMMENT ON COLUMN "lkp_disbursement_status"."code" IS 'e.g. PREPARED, RELEASED, SETTLED, RETURNED';

COMMENT ON COLUMN "lkp_disbursement_status"."is_released" IS 'Whether funds have been released for transfer';

COMMENT ON COLUMN "lkp_disbursement_status"."is_settled" IS 'Whether the transfer has fully settled';

COMMENT ON COLUMN "lkp_disbursement_status"."is_error_state" IS 'Whether this state indicates a disbursement failure';

COMMENT ON COLUMN "payroll_context"."payroll_context_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "payroll_context"."payroll_context_code" IS 'Short human-readable code, e.g. BIWK-HQ-USD';

COMMENT ON COLUMN "payroll_context"."payroll_context_name" IS 'Display name, e.g. HQ Biweekly Salaried';

COMMENT ON COLUMN "payroll_context"."legal_entity_id" IS 'FK → org_unit.org_unit_id (LEGAL_ENTITY type)';

COMMENT ON COLUMN "payroll_context"."pay_frequency_id" IS 'FK → lkp_pay_frequency.id';

COMMENT ON COLUMN "payroll_context"."compensation_rate_type_id" IS 'FK → lkp_compensation_rate_type.id (SALARY, HOURLY, etc.). Classifies the compensation basis for this pay group.';

COMMENT ON COLUMN "payroll_context"."context_status" IS 'DEFINED | CONFIGURED | ACTIVE | SUSPENDED | CLOSED';

COMMENT ON COLUMN "payroll_context"."parent_payroll_context_id" IS 'Lineage — prior context version this supersedes';

COMMENT ON COLUMN "payroll_context"."root_payroll_context_id" IS 'Root context in lineage chain';

COMMENT ON COLUMN "payroll_context"."context_change_reason_code" IS 'Reason for this version e.g. CALENDAR_CHANGE';

COMMENT ON COLUMN "payroll_context"."effective_end_date" IS 'Null = currently active';

COMMENT ON COLUMN "payroll_context"."pay_date_convention" IS 'Convention code for monthly/semi-monthly: MONTH_END, MID_MONTH, FIRST_FOLLOWING, FIXED_25, SM_15_AND_END, SM_1_AND_15, SM_10_AND_25. Null for offset-model frequencies (weekly, biweekly).';

COMMENT ON COLUMN "payroll_context"."pay_date_offset_days" IS 'Days after period end to pay. Used by offset-model frequencies (weekly, biweekly). Ignored when pay_date_convention is set.';

COMMENT ON COLUMN "payroll_context"."cutoff_offset_days" IS 'Days before pay_date that input cutoff falls. Applied to all frequencies.';

COMMENT ON COLUMN "payroll_context"."extra_period_policy" IS 'Policy for 53rd (weekly) or 27th (biweekly) period in a year: EXTRA_SPECIAL | ABSORB_PREV | ABSORB_NEXT';

COMMENT ON COLUMN "payroll_context"."three_paycheck_month_rule" IS 'PRORATE | SKIP — how benefit deductions are handled in a 3-paycheck month';

COMMENT ON COLUMN "payroll_period"."period_id" IS 'System-generated. Also used as calendar_context_id in accumulator_balance and payroll_check.';

COMMENT ON COLUMN "payroll_period"."payroll_context_id" IS 'FK → payroll_context.payroll_context_id';

COMMENT ON COLUMN "payroll_period"."period_year" IS 'Calendar year e.g. 2026';

COMMENT ON COLUMN "payroll_period"."period_number" IS 'Period sequence within the year, 1-based';

COMMENT ON COLUMN "payroll_period"."pay_date" IS 'Immutable once runs reference this period';

COMMENT ON COLUMN "payroll_period"."input_cutoff_date" IS 'Last date payroll inputs are accepted';

COMMENT ON COLUMN "payroll_period"."calculation_date" IS 'Scheduled calculation date; null until set';

COMMENT ON COLUMN "payroll_period"."correction_window_close_date" IS 'Last date corrections are permitted';

COMMENT ON COLUMN "payroll_period"."calendar_status" IS 'OPEN | IN_PROGRESS | CALCULATED | APPROVED | RELEASED | CLOSED';

COMMENT ON COLUMN "payroll_period"."parent_calendar_entry_id" IS 'Prior calendar entry in lineage';

COMMENT ON COLUMN "payroll_period"."root_calendar_entry_id" IS 'Root calendar entry in lineage chain';

COMMENT ON COLUMN "payroll_run"."run_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "payroll_run"."payroll_context_id" IS 'The payroll group this run belongs to';

COMMENT ON COLUMN "payroll_run"."period_id" IS 'The payroll calendar period';

COMMENT ON COLUMN "payroll_run"."pay_date" IS 'Inherited from calendar entry; immutable';

COMMENT ON COLUMN "payroll_run"."run_type_id" IS 'FK → lkp_run_type.id';

COMMENT ON COLUMN "payroll_run"."run_status_id" IS 'FK → lkp_run_status.id';

COMMENT ON COLUMN "payroll_run"."parent_run_id" IS 'Links correction or rerun to original run';

COMMENT ON COLUMN "payroll_run"."related_run_group_id" IS 'Groups related supplemental or adjustment runs';

COMMENT ON COLUMN "payroll_run"."rule_and_config_version_ref" IS 'Snapshot of configuration version used';

COMMENT ON COLUMN "payroll_run"."temporal_override_date" IS 'Override date at initiation time; null if no override';

COMMENT ON COLUMN "run_scope"."run_scope_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "run_scope"."parent_run_id" IS 'References the finalized parent payroll_run';

COMMENT ON COLUMN "run_scope"."scope_type_id" IS 'FK → lkp_scope_type.id';

COMMENT ON COLUMN "run_scope"."scope_status_id" IS 'FK → lkp_scope_status.id';

COMMENT ON COLUMN "run_scope"."population_method_id" IS 'FK → lkp_population_method.id';

COMMENT ON COLUMN "run_scope"."population_definition" IS 'Serialized query or explicit list reference';

COMMENT ON COLUMN "run_scope"."priority_level" IS 'STANDARD, CATCH_UP, RECOVERY, EMERGENCY';

COMMENT ON COLUMN "run_scope"."execution_result" IS 'SUCCESS, FAILED';

COMMENT ON COLUMN "payroll_run_result_set"."payroll_run_result_set_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "payroll_run_result_set"."run_scope_id" IS 'Present when result set is from a scoped execution';

COMMENT ON COLUMN "payroll_run_result_set"."source_period_id" IS 'Original payroll period';

COMMENT ON COLUMN "payroll_run_result_set"."execution_period_id" IS 'Period during which execution occurred';

COMMENT ON COLUMN "payroll_run_result_set"."parent_payroll_run_result_set_id" IS 'Prior result set in lineage';

COMMENT ON COLUMN "payroll_run_result_set"."root_payroll_run_result_set_id" IS 'Root result set in lineage chain';

COMMENT ON COLUMN "payroll_run_result_set"."result_set_status_id" IS 'FK → lkp_result_set_status.id';

COMMENT ON COLUMN "payroll_run_result_set"."result_set_type_id" IS 'FK → lkp_result_set_type.id';

COMMENT ON COLUMN "employee_payroll_result"."employee_payroll_result_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "employee_payroll_result"."employment_id" IS 'Payroll anchor — never person_id';

COMMENT ON COLUMN "employee_payroll_result"."parent_employee_payroll_result_id" IS 'Prior worker-level result in lineage';

COMMENT ON COLUMN "employee_payroll_result"."root_employee_payroll_result_id" IS 'Root worker-level result in lineage chain';

COMMENT ON COLUMN "employee_payroll_result"."result_status_id" IS 'FK → lkp_employee_result_status.id';

COMMENT ON COLUMN "earnings_result_line"."quantity" IS 'Hours, units, or quantity';

COMMENT ON COLUMN "tax_result_line"."employer_flag" IS 'True for employer-side tax lines';

COMMENT ON COLUMN "payroll_check"."check_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "payroll_check"."check_number" IS 'Human-readable; unique within context';

COMMENT ON COLUMN "payroll_check"."payment_method_id" IS 'FK → lkp_payment_method.id';

COMMENT ON COLUMN "payroll_check"."payment_context_id" IS 'FK → lkp_payment_context.id';

COMMENT ON COLUMN "payroll_check"."check_status_id" IS 'FK → lkp_check_status.id';

COMMENT ON COLUMN "payroll_check"."corrects_check_id" IS 'Reference to original if this is a correction check';

COMMENT ON COLUMN "payroll_item"."payroll_item_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "payroll_item"."result_class_id" IS 'FK → lkp_result_class.id';

COMMENT ON COLUMN "payroll_item"."item_status_id" IS 'FK → lkp_item_status.id';

COMMENT ON COLUMN "accumulator_definition"."accumulator_definition_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "accumulator_definition"."accumulator_family_id" IS 'FK → lkp_accumulator_family.id';

COMMENT ON COLUMN "accumulator_definition"."scope_type_id" IS 'FK → lkp_accumulator_scope_type.id';

COMMENT ON COLUMN "accumulator_definition"."period_context_id" IS 'FK → lkp_period_context.id';

COMMENT ON COLUMN "accumulator_definition"."reset_type" IS 'CALENDAR_YEAR, PLAN_YEAR, QUARTER, NONE, CONDITIONAL';

COMMENT ON COLUMN "accumulator_impact"."accumulator_impact_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "accumulator_impact"."payroll_run_result_set_id" IS 'Present for run-level impacts';

COMMENT ON COLUMN "accumulator_impact"."employee_payroll_result_id" IS 'Present for employee-level impacts';

COMMENT ON COLUMN "accumulator_impact"."impact_status_id" IS 'FK → lkp_impact_status.id';

COMMENT ON COLUMN "accumulator_impact"."impact_source_type_id" IS 'FK → lkp_impact_source_type.id';

COMMENT ON COLUMN "accumulator_impact"."source_object_id" IS 'Source result line reference';

COMMENT ON COLUMN "accumulator_impact"."posting_direction_id" IS 'FK → lkp_posting_direction.id';

COMMENT ON COLUMN "accumulator_impact"."scope_type_id" IS 'FK → lkp_accumulator_scope_type.id';

COMMENT ON COLUMN "accumulator_impact"."prior_accumulator_impact_id" IS 'Links correction/reversal to original impact';

COMMENT ON COLUMN "accumulator_contribution"."contribution_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "accumulator_contribution"."accumulator_id" IS 'Links to accumulator_balance';

COMMENT ON COLUMN "accumulator_contribution"."accumulator_impact_id" IS 'Source impact that generated this contribution';

COMMENT ON COLUMN "accumulator_contribution"."parent_contribution_id" IS 'Prior contribution in correction chain';

COMMENT ON COLUMN "accumulator_contribution"."root_contribution_id" IS 'Root contribution in lineage chain';

COMMENT ON COLUMN "accumulator_contribution"."scope_type_id" IS 'FK → lkp_accumulator_scope_type.id';

COMMENT ON COLUMN "accumulator_contribution"."contribution_type_id" IS 'FK → lkp_contribution_type.id';

COMMENT ON COLUMN "accumulator_balance"."accumulator_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "accumulator_balance"."accumulator_family_id" IS 'FK → lkp_accumulator_family.id';

COMMENT ON COLUMN "accumulator_balance"."scope_type_id" IS 'FK → lkp_accumulator_scope_type.id';

COMMENT ON COLUMN "accumulator_balance"."participant_id" IS 'Required if scope includes employee';

COMMENT ON COLUMN "accumulator_balance"."employer_id" IS 'Required if scope includes employer';

COMMENT ON COLUMN "accumulator_balance"."period_context_id" IS 'FK → lkp_period_context.id';

COMMENT ON COLUMN "accumulator_balance"."balance_status_id" IS 'FK → lkp_accumulator_balance_status.id';

COMMENT ON COLUMN "payroll_profile"."payroll_profile_id" IS 'System-generated. Immutable.';

COMMENT ON COLUMN "payroll_profile"."employment_id" IS 'FK → employment.employment_id. One enrollment per employment.';

COMMENT ON COLUMN "payroll_profile"."person_id" IS 'FK → person.person_id. Denormalised for query convenience.';

COMMENT ON COLUMN "payroll_profile"."payroll_context_id" IS 'FK → payroll_context.payroll_context_id';

COMMENT ON COLUMN "payroll_profile"."enrollment_status" IS 'ACTIVE | SUSPENDED | FINAL_PAY_PENDING | TERMINATED';

COMMENT ON COLUMN "payroll_profile"."effective_start_date" IS 'Date the enrollment became effective';

COMMENT ON COLUMN "payroll_profile"."effective_end_date" IS 'Null = currently active';

COMMENT ON COLUMN "payroll_profile"."final_pay_flag" IS 'Set by TERMINATION event; signals final pay required';

COMMENT ON COLUMN "payroll_profile"."blocking_tasks_cleared" IS 'Set TRUE when OnboardingBlockingTasksCompletePayload received. FALSE excludes employee from payroll run population.';

COMMENT ON COLUMN "payroll_profile"."enrollment_source" IS 'AUTO_HIRE | MANUAL';

COMMENT ON COLUMN "payroll_run_exception"."run_exception_id" IS 'System-generated';

COMMENT ON COLUMN "payroll_run_exception"."run_id" IS 'FK → payroll_run.run_id';

COMMENT ON COLUMN "payroll_run_exception"."employment_id" IS 'Employee excluded from this run';

COMMENT ON COLUMN "payroll_run_exception"."exception_code" IS 'BLOCKING_TASKS_INCOMPLETE | INACTIVE_PROFILE | etc.';

COMMENT ON COLUMN "payroll_run_exception"."exception_message" IS 'Human-readable detail for audit/reporting';

COMMENT ON COLUMN "payroll_run_exception"."created_timestamp" IS 'Server UTC time when exception was recorded';

COMMENT ON COLUMN "funding_result_set"."funding_status_id" IS 'FK → lkp_funding_status.id';

COMMENT ON COLUMN "remittance_result_set"."remittance_status_id" IS 'FK → lkp_remittance_status.id';

COMMENT ON COLUMN "disbursement_result_set"."disbursement_status_id" IS 'FK → lkp_disbursement_status.id';

COMMENT ON COLUMN "tax_jurisdiction"."jurisdiction_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_jurisdiction"."jurisdiction_code" IS 'e.g. US-FED, US-NY, CA-FED, BB';

COMMENT ON COLUMN "tax_jurisdiction"."country_code" IS 'ISO 3166-1 alpha-2';

COMMENT ON COLUMN "legal_entity_jurisdiction"."legal_entity_id" IS 'FK → org_unit.org_unit_id (legal entity rows only)';

COMMENT ON COLUMN "legal_entity_jurisdiction"."jurisdiction_id" IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "payroll_calculation_steps"."step_id" IS 'Auto-generated';

COMMENT ON COLUMN "payroll_calculation_steps"."jurisdiction_id" IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "payroll_calculation_steps"."step_code" IS 'e.g. US_FED_INCOME_TAX, BB_NIS. Used as StepCode in ICalculationStep';

COMMENT ON COLUMN "payroll_calculation_steps"."step_type" IS 'STANDARD_DEDUCTION | ALLOWANCE | PROGRESSIVE_BRACKET | CREDIT | FLAT_RATE | TIERED_FLAT | PERCENTAGE_OF_PRIOR';

COMMENT ON COLUMN "payroll_calculation_steps"."calculation_category" IS 'PRETAX_BENEFIT | DEDUCTION_ALLOWANCE | INCOME_TAX | CREDIT | SOCIAL_INSURANCE | SUBNATIONAL_TAX | DERIVED_TAX | POSTTAX | EMPLOYER_CONTRIBUTION';

COMMENT ON COLUMN "payroll_calculation_steps"."sequence_number" IS 'Execution order within pipeline: 100-199 pre-tax benefits, 200-299 deductions/allowances, 300-399 national income tax, 400-499 credits, 500-599 social insurance, 600-699 sub-national income tax, 700-799 derived taxes, 800-899 post-tax deductions, 900-999 employer contributions';

COMMENT ON COLUMN "payroll_calculation_steps"."applies_to" IS 'EMPLOYEE | EMPLOYER | BOTH';

COMMENT ON COLUMN "payroll_calculation_steps"."reduces_income_tax_wages" IS 'TRUE for pre-tax steps that reduce IncomeTaxableWages';

COMMENT ON COLUMN "payroll_calculation_steps"."reduces_fica_wages" IS 'TRUE for pre-tax steps that also reduce FicaTaxableWages';

COMMENT ON COLUMN "payroll_calculation_steps"."status_code" IS 'DRAFT | PENDING_REVIEW | APPROVED | ACTIVE | ARCHIVED';

COMMENT ON COLUMN "tax_filing_status"."filing_status_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_filing_status"."jurisdiction_id" IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "tax_filing_status"."filing_status_code" IS 'e.g. SINGLE, MFJ, MFS, HOH';

COMMENT ON COLUMN "tax_brackets"."bracket_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_brackets"."step_code" IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_brackets"."filing_status_code" IS 'NULL = applies to all filing statuses for this step';

COMMENT ON COLUMN "tax_brackets"."effective_to" IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_brackets"."lower_limit" IS 'Annual income lower bound (inclusive)';

COMMENT ON COLUMN "tax_brackets"."upper_limit" IS 'NULL = no upper limit (top bracket)';

COMMENT ON COLUMN "tax_brackets"."rate" IS 'Marginal rate e.g. 0.220000 = 22%';

COMMENT ON COLUMN "tax_flat_rates"."flat_rate_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_flat_rates"."step_code" IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_flat_rates"."effective_to" IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_flat_rates"."rate" IS 'e.g. 0.062000 = 6.2%';

COMMENT ON COLUMN "tax_flat_rates"."wage_base" IS 'Annual wage ceiling; NULL = no cap on taxable base';

COMMENT ON COLUMN "tax_flat_rates"."period_cap_amount" IS 'Maximum deduction per pay period';

COMMENT ON COLUMN "tax_flat_rates"."annual_cap_amount" IS 'Maximum deduction per calendar year; enforced via YTD accumulator';

COMMENT ON COLUMN "tax_flat_rates"."depends_on_step_code" IS 'PERCENTAGE_OF_PRIOR only — step whose result this rate is applied to';

COMMENT ON COLUMN "tax_tiered_brackets"."tiered_bracket_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_tiered_brackets"."step_code" IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_tiered_brackets"."effective_to" IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_tiered_brackets"."lower_limit" IS 'Annual earnings lower bound for this tier';

COMMENT ON COLUMN "tax_tiered_brackets"."upper_limit" IS 'NULL = no upper limit';

COMMENT ON COLUMN "tax_tiered_brackets"."period_cap_amount" IS 'Per-period contribution cap within this tier';

COMMENT ON COLUMN "tax_tiered_brackets"."annual_cap_amount" IS 'Annual contribution cap within this tier; enforced via YTD accumulator';

COMMENT ON COLUMN "tax_allowances"."allowance_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_allowances"."step_code" IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_allowances"."filing_status_code" IS 'NULL = applies to all filing statuses';

COMMENT ON COLUMN "tax_allowances"."effective_to" IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_allowances"."annual_amount" IS 'Annual deduction amount; divided by PayPeriodsPerYear at runtime';

COMMENT ON COLUMN "tax_credits"."credit_id" IS 'Auto-generated';

COMMENT ON COLUMN "tax_credits"."step_code" IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_credits"."effective_to" IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_credits"."annual_amount" IS 'Gross credit base e.g. Canada BPA CAD 16,129';

COMMENT ON COLUMN "tax_credits"."credit_rate" IS 'Rate applied to annual_amount e.g. 0.150000 = 15% for Canada BPA';

COMMENT ON COLUMN "lkp_tax_form_type"."id" IS 'Auto-generated';

COMMENT ON COLUMN "employee_tax_form_submission"."submission_id" IS 'System-generated';

COMMENT ON COLUMN "employee_tax_form_submission"."employment_id" IS 'FK → employment.employment_id';

COMMENT ON COLUMN "employee_tax_form_submission"."jurisdiction_id" IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "employee_tax_form_submission"."form_type_id" IS 'FK → lkp_tax_form_type.id';

COMMENT ON COLUMN "employee_tax_form_submission"."source_document_id" IS 'FK → HRIS document store; nullable until scan attached';

COMMENT ON COLUMN "employee_tax_form_submission"."submitted_date" IS 'Date employee signed and submitted the form';

COMMENT ON COLUMN "employee_tax_form_submission"."exempt_flag" IS 'Employee claimed withholding exemption on the form';

COMMENT ON COLUMN "employee_tax_form_submission"."effective_to" IS 'NULL = currently active; set when superseded by a new filing';

COMMENT ON COLUMN "employee_tax_form_detail"."submission_id" IS 'FK → employee_tax_form_submission.submission_id';

COMMENT ON COLUMN "employee_tax_form_detail"."filing_status_code" IS 'W-4 Step 1c, IT-2104 filing status, etc. NULL for TD1/TD1X.';

COMMENT ON COLUMN "employee_tax_form_detail"."allowance_count" IS 'W-4 legacy Step 5, or state allowance count.';

COMMENT ON COLUMN "employee_tax_form_detail"."additional_withholding" IS 'W-4 Step 4c / state extra withholding per period.';

COMMENT ON COLUMN "employee_tax_form_detail"."is_legacy_form" IS 'TRUE = pre-2020 W-4 (allowances format).';

COMMENT ON COLUMN "employee_tax_form_detail"."other_income_amount" IS 'W-4 2020+ Step 4a — added to annualized base before bracket walk.';

COMMENT ON COLUMN "employee_tax_form_detail"."deductions_amount" IS 'W-4 2020+ Step 4b — subtracted from annualized base before bracket walk.';

COMMENT ON COLUMN "employee_tax_form_detail"."credits_amount" IS 'W-4 2020+ Step 3 — subtracted from annual tax after bracket walk.';

COMMENT ON COLUMN "employee_tax_form_detail"."claim_code" IS 'TD1/TD1X/BB-TD4: CRA standard claim code 1–10.';

COMMENT ON COLUMN "employee_tax_form_detail"."total_claim_amount" IS 'TD1/TD1X/BB-TD4: custom worksheet total.';

COMMENT ON COLUMN "employee_tax_form_detail"."additional_tax_amount" IS 'TD1/TD1X/BB-TD4: additional tax to deduct per period.';

COMMENT ON COLUMN "form_field_definition"."field_definition_id" IS 'Auto-generated';

COMMENT ON COLUMN "form_field_definition"."form_type_code" IS 'FK → lkp_tax_form_type.code';

COMMENT ON COLUMN "form_field_definition"."effective_to" IS 'NULL = currently effective';

COMMENT ON COLUMN "form_field_definition"."field_key" IS 'Stable identifier for this field within the form type';

COMMENT ON COLUMN "form_field_definition"."field_type" IS 'TEXT | INTEGER | DECIMAL | BOOLEAN | ENUM | DATE';

COMMENT ON COLUMN "form_field_definition"."section_key" IS 'Groups fields into form sections';

COMMENT ON COLUMN "form_field_definition"."detail_column_name" IS 'Physical column in employee_tax_form_detail';

COMMENT ON COLUMN "form_field_definition"."promotes_to_column" IS 'CalculationContext property that receives this value';

COMMENT ON COLUMN "form_field_definition"."validation_rules_json" IS 'ANSI TEXT — structured rule definition';

COMMENT ON COLUMN "form_field_definition"."visibility_rule_json" IS 'ANSI TEXT — conditional display rule';

COMMENT ON COLUMN "form_field_definition"."enum_values_json" IS 'ANSI TEXT — allowed values for ENUM field_type';

COMMENT ON COLUMN "form_field_definition"."status_code" IS 'DRAFT | PENDING_REVIEW | APPROVED | ACTIVE | ARCHIVED';

COMMENT ON COLUMN "configuration_audit_log"."audit_log_id" IS 'Auto-generated';

COMMENT ON COLUMN "configuration_audit_log"."entity_name" IS 'Table name, e.g. payroll_calculation_steps';

COMMENT ON COLUMN "configuration_audit_log"."entity_id_text" IS 'String representation of entity PK';

COMMENT ON COLUMN "configuration_audit_log"."action_code" IS 'CREATED | SUBMITTED_FOR_REVIEW | APPROVED | ACTIVATED | ARCHIVED | REJECTED | EDITED';

COMMENT ON COLUMN "configuration_audit_log"."snapshot_json" IS 'Full row state at transition time; ANSI TEXT for portability';

COMMENT ON COLUMN "deduction"."tax_treatment" IS 'PRE_TAX | POST_TAX';

COMMENT ON COLUMN "deduction"."status" IS 'ACTIVE | INACTIVE';

COMMENT ON COLUMN "deduction"."calculation_mode" IS 'FIXED_ANNUAL | FIXED_MONTHLY | FIXED_PER_PERIOD | PCT_PRE_TAX | PCT_POST_TAX | COVERAGE_BASED';

COMMENT ON COLUMN "deduction"."wage_base" IS 'ALL | REGULAR_ONLY | ELIGIBLE_ONLY | OT_ONLY — only valid for PCT modes';

COMMENT ON COLUMN "deduction"."age_as_of_rule" IS 'JAN_1 | PAY_DATE — only valid for COVERAGE_BASED mode';

COMMENT ON COLUMN "deduction_rate_table"."deduction_id" IS 'FK → deduction.deduction_id';

COMMENT ON COLUMN "deduction_rate_table"."rate_type" IS 'COVERAGE_TIER | AGE_BAND | SALARY_BAND';

COMMENT ON COLUMN "deduction_rate_entry"."rate_table_id" IS 'FK → deduction_rate_table.rate_table_id';

COMMENT ON COLUMN "deduction_rate_entry"."tier_code" IS 'EE_ONLY | EE_SPOUSE | EE_CHILD | FAMILY — for COVERAGE_TIER tables';

COMMENT ON COLUMN "deduction_rate_entry"."band_min" IS 'Lower bound inclusive — for AGE_BAND and SALARY_BAND tables';

COMMENT ON COLUMN "deduction_rate_entry"."band_max" IS 'Upper bound inclusive; null = no upper limit';

COMMENT ON COLUMN "deduction_rate_entry"."employee_rate" IS 'Monthly flat amount (COVERAGE_TIER) | rate per $1,000 coverage (AGE_BAND) | rate per $1 salary (SALARY_BAND)';

COMMENT ON COLUMN "deduction_employer_match"."deduction_id" IS 'FK → deduction.deduction_id';

COMMENT ON COLUMN "deduction_employer_match"."employee_group_id" IS 'Null = applies to all employees';

COMMENT ON COLUMN "deduction_employer_match"."match_rate" IS 'e.g. 0.500000 = 50% match of employee contribution';

COMMENT ON COLUMN "deduction_employer_match"."match_cap_pct_of_gross" IS 'Match applies on up to this fraction of gross; exactly one cap must be set';

COMMENT ON COLUMN "deduction_employer_match"."match_cap_annual_amount" IS 'Dollar cap per year; exactly one cap must be set';

COMMENT ON COLUMN "deduction_employer_match"."match_type" IS 'PER_PERIOD | ANNUAL_TRUE_UP';

COMMENT ON COLUMN "benefit_deduction_election"."employment_id" IS 'FK → employment.employment_id';

COMMENT ON COLUMN "benefit_deduction_election"."deduction_id" IS 'FK → deduction.deduction_id';

COMMENT ON COLUMN "benefit_deduction_election"."tax_treatment" IS 'PRE_TAX | POST_TAX';

COMMENT ON COLUMN "benefit_deduction_election"."contribution_pct" IS 'For PCT_PRE_TAX / PCT_POST_TAX modes — fraction of wage base';

COMMENT ON COLUMN "benefit_deduction_election"."coverage_tier" IS 'EE_ONLY | EE_SPOUSE | EE_CHILD | FAMILY — for COVERAGE_BASED mode';

COMMENT ON COLUMN "benefit_deduction_election"."annual_coverage_amount" IS 'Face amount for life/AD&D — used in age-band rate lookup';

COMMENT ON COLUMN "benefit_deduction_election"."annual_election_amount" IS 'System-computed annualised deduction; populated on election activation';

COMMENT ON COLUMN "benefit_deduction_election"."monthly_election_amount" IS 'System-computed monthly equivalent; populated on election activation';

COMMENT ON COLUMN "benefit_deduction_election"."partial_period_rule" IS 'PRORATE_DAYS | FULL_PERIOD | FIRST_FULL_PERIOD';

COMMENT ON COLUMN "benefit_deduction_election"."status" IS 'PENDING | ACTIVE | SUSPENDED | SUPERSEDED | TERMINATED';

COMMENT ON COLUMN "benefit_deduction_election"."source" IS 'MANUAL | IMPORT | API';

ALTER TABLE "legal_entity_jurisdiction" ADD FOREIGN KEY ("jurisdiction_id") REFERENCES "tax_jurisdiction" ("jurisdiction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payroll_calculation_steps" ADD FOREIGN KEY ("jurisdiction_id") REFERENCES "tax_jurisdiction" ("jurisdiction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tax_filing_status" ADD FOREIGN KEY ("jurisdiction_id") REFERENCES "tax_jurisdiction" ("jurisdiction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_tax_form_submission" ADD FOREIGN KEY ("jurisdiction_id") REFERENCES "tax_jurisdiction" ("jurisdiction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_tax_form_submission" ADD FOREIGN KEY ("form_type_id") REFERENCES "lkp_tax_form_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_tax_form_detail" ADD FOREIGN KEY ("submission_id") REFERENCES "employee_tax_form_submission" ("submission_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "deduction_rate_table" ADD FOREIGN KEY ("deduction_id") REFERENCES "deduction" ("deduction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "deduction_rate_entry" ADD FOREIGN KEY ("rate_table_id") REFERENCES "deduction_rate_table" ("rate_table_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "deduction_employer_match" ADD FOREIGN KEY ("deduction_id") REFERENCES "deduction" ("deduction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "benefit_deduction_election" ADD FOREIGN KEY ("deduction_id") REFERENCES "deduction" ("deduction_id") DEFERRABLE INITIALLY IMMEDIATE;
