-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-04-28T20:18:47.996Z

CREATE TABLE "lkp_person_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "allows_employment" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employee_event_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "event_category" varchar(30) NOT NULL,
  "is_separation" boolean NOT NULL DEFAULT false,
  "triggers_onboarding" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employment_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_w2" boolean NOT NULL DEFAULT true,
  "benefits_eligible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employment_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_payroll_active" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_full_part_time_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "min_hours_week" decimal(5,2),
  "max_hours_week" decimal(5,2),
  "benefits_eligible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_regular_temporary_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "has_end_date" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_flsa_classification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "overtime_eligible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_flsa_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "flsa_classification_id" integer,
  "overtime_eligible" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_eeo_category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "eeo1_category_num" varchar(10) NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_assignment_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_primary" boolean NOT NULL DEFAULT false,
  "allows_overlap" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_assignment_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_compensation_rate_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_annualized" boolean NOT NULL DEFAULT false,
  "unit_of_measure" varchar(30),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_compensation_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_payable" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_pay_frequency" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "periods_per_year" int NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_payroll_impact_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "affects_gross_pay" boolean NOT NULL DEFAULT true,
  "pay_percentage" decimal(5,2),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_approval_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_approved_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_leave_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "payroll_impact_type_id" integer,
  "is_accrued" boolean NOT NULL DEFAULT true,
  "is_protected" boolean NOT NULL DEFAULT false,
  "requires_documentation" boolean NOT NULL DEFAULT false,
  "max_days_per_year" int,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_leave_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_on_leave" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_document_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "requires_signature" boolean NOT NULL DEFAULT false,
  "retention_days" int,
  "is_employee_visible" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_document_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_valid" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_onboarding_plan_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_onboarding_task_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "document_type_id" integer,
  "default_due_days" int,
  "is_employee_action" boolean NOT NULL DEFAULT true,
  "is_blocking" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_onboarding_task_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "approval_status_id" integer,
  "is_complete_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_org_unit_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "allows_children" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_org_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_operational" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_work_location_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_on_site" boolean NOT NULL DEFAULT true,
  "requires_address" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_job_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_hirable" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_position_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_fillable" boolean NOT NULL DEFAULT true,
  "is_occupied" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

COMMENT ON TABLE "lkp_person_status" IS 'Lifecycle status of a person record';

COMMENT ON COLUMN "lkp_person_status"."id" IS 'SERIAL primary key';

COMMENT ON COLUMN "lkp_person_status"."code" IS 'e.g. ACTIVE, INACTIVE, DECEASED, RESTRICTED, ARCHIVED';

COMMENT ON COLUMN "lkp_person_status"."allows_employment" IS 'Whether this status permits active employment records';

COMMENT ON TABLE "lkp_employee_event_type" IS 'Classifies employee lifecycle events (hire, termination, transfer, etc.)';

COMMENT ON COLUMN "lkp_employee_event_type"."code" IS 'e.g. HIRE, REHIRE, TERMINATION, PROMOTION, TRANSFER, LOA_START, LOA_RETURN';

COMMENT ON COLUMN "lkp_employee_event_type"."event_category" IS 'Grouping: ONBOARDING, SEPARATION, MOVEMENT, COMPENSATION, LEAVE';

COMMENT ON COLUMN "lkp_employee_event_type"."is_separation" IS 'True if this event ends employment';

COMMENT ON COLUMN "lkp_employee_event_type"."triggers_onboarding" IS 'True if this event initiates onboarding workflow';

COMMENT ON TABLE "lkp_employment_type" IS 'Worker classification type (Employee, Contractor, Intern, etc.)';

COMMENT ON COLUMN "lkp_employment_type"."code" IS 'e.g. EMPLOYEE, CONTRACTOR, INTERN, VOLUNTEER';

COMMENT ON COLUMN "lkp_employment_type"."is_w2" IS 'W-2 tax treatment (vs 1099)';

COMMENT ON COLUMN "lkp_employment_type"."benefits_eligible" IS 'Default benefits eligibility';

COMMENT ON TABLE "lkp_employment_status" IS 'Current state of an employment record';

COMMENT ON COLUMN "lkp_employment_status"."code" IS 'e.g. ACTIVE, ON_LEAVE, SUSPENDED, TERMINATED, RETIRED';

COMMENT ON COLUMN "lkp_employment_status"."is_payroll_active" IS 'Whether employment feeds active payroll';

COMMENT ON TABLE "lkp_full_part_time_status" IS 'Full-time vs part-time classification (ACA, benefits eligibility)';

COMMENT ON COLUMN "lkp_full_part_time_status"."code" IS 'e.g. FULL_TIME, PART_TIME, PRN, ON_CALL';

COMMENT ON COLUMN "lkp_full_part_time_status"."min_hours_week" IS 'Minimum weekly hours threshold for this classification';

COMMENT ON COLUMN "lkp_full_part_time_status"."max_hours_week" IS 'Maximum weekly hours threshold';

COMMENT ON COLUMN "lkp_full_part_time_status"."benefits_eligible" IS 'ACA / plan eligibility default';

COMMENT ON TABLE "lkp_regular_temporary_status" IS 'Regular vs temporary/seasonal employment classification';

COMMENT ON COLUMN "lkp_regular_temporary_status"."code" IS 'e.g. REGULAR, TEMPORARY, SEASONAL, PROJECT_BASED';

COMMENT ON COLUMN "lkp_regular_temporary_status"."has_end_date" IS 'Whether assignments of this type require a defined end date';

COMMENT ON TABLE "lkp_flsa_classification" IS 'FLSA exemption classification (Executive, Administrative, Professional, etc.)';

COMMENT ON COLUMN "lkp_flsa_classification"."code" IS 'e.g. EXECUTIVE, ADMINISTRATIVE, PROFESSIONAL, COMPUTER, OUTSIDE_SALES, HIGHLY_COMPENSATED';

COMMENT ON COLUMN "lkp_flsa_classification"."overtime_eligible" IS 'Whether this classification is eligible for overtime';

COMMENT ON TABLE "lkp_flsa_status" IS 'FLSA exemption status assigned to a position or employee';

COMMENT ON COLUMN "lkp_flsa_status"."code" IS 'e.g. EXEMPT, NON_EXEMPT, EXEMPT_ADMIN, EXEMPT_PROF, EXEMPT_COMPUTER, EXEMPT_SALES, EXEMPT_HCE';

COMMENT ON COLUMN "lkp_flsa_status"."flsa_classification_id" IS 'FK → lkp_flsa_classification.id';

COMMENT ON COLUMN "lkp_flsa_status"."overtime_eligible" IS 'Whether OT applies';

COMMENT ON TABLE "lkp_eeo_category" IS 'EEO-1 job category for federal compliance reporting';

COMMENT ON COLUMN "lkp_eeo_category"."code" IS 'e.g. EXEC_SR_OFFICIALS, FIRST_MID_OFFICIALS, PROFESSIONALS';

COMMENT ON COLUMN "lkp_eeo_category"."eeo1_category_num" IS 'Official EEO-1 numeric category identifier';

COMMENT ON TABLE "lkp_assignment_type" IS 'Type of work assignment (Primary, Secondary, Acting, etc.)';

COMMENT ON COLUMN "lkp_assignment_type"."code" IS 'e.g. PRIMARY, SECONDARY, ADDITIONAL, ACTING, INTERIM';

COMMENT ON COLUMN "lkp_assignment_type"."is_primary" IS 'Whether this type designates the primary/home assignment';

COMMENT ON COLUMN "lkp_assignment_type"."allows_overlap" IS 'Whether multiple assignments of this type can coexist';

COMMENT ON TABLE "lkp_assignment_status" IS 'Lifecycle status of a work assignment';

COMMENT ON COLUMN "lkp_assignment_status"."code" IS 'e.g. ACTIVE, INACTIVE, PENDING, ENDED, SUSPENDED';

COMMENT ON COLUMN "lkp_assignment_status"."is_active_state" IS 'Whether this status represents an active assignment';

COMMENT ON TABLE "lkp_compensation_rate_type" IS 'How compensation is measured (salary, hourly, commission, etc.)';

COMMENT ON COLUMN "lkp_compensation_rate_type"."code" IS 'e.g. SALARY, HOURLY, DAILY, PIECE_RATE, COMMISSION, STIPEND';

COMMENT ON COLUMN "lkp_compensation_rate_type"."is_annualized" IS 'Whether the rate is expressed as an annual figure';

COMMENT ON COLUMN "lkp_compensation_rate_type"."unit_of_measure" IS 'Rate unit: YEAR, HOUR, DAY, UNIT, PERCENT, PERIOD';

COMMENT ON TABLE "lkp_compensation_status" IS 'Lifecycle status of a compensation record';

COMMENT ON COLUMN "lkp_compensation_status"."code" IS 'e.g. PROPOSED, APPROVED, ACTIVE, FROZEN, ENDED';

COMMENT ON COLUMN "lkp_compensation_status"."approval_status_id" IS 'FK → lkp_approval_status.id';

COMMENT ON COLUMN "lkp_compensation_status"."is_payable" IS 'Whether compensation is disbursable in this state';

COMMENT ON TABLE "lkp_pay_frequency" IS 'Pay cycle frequency (weekly, biweekly, semimonthly, monthly, etc.)';

COMMENT ON COLUMN "lkp_pay_frequency"."code" IS 'e.g. WEEKLY, BIWEEKLY, SEMIMONTHLY, MONTHLY, QUARTERLY, ANNUAL';

COMMENT ON COLUMN "lkp_pay_frequency"."periods_per_year" IS 'Number of pay periods per year (52, 26, 24, 12, 4, 1)';

COMMENT ON TABLE "lkp_payroll_impact_type" IS 'How an event or leave type impacts payroll (paid, unpaid, partial, etc.)';

COMMENT ON COLUMN "lkp_payroll_impact_type"."code" IS 'e.g. PAID, UNPAID, PARTIAL_PAY, REDUCED_RATE, COMPANY_FUNDED, STATE_FUNDED';

COMMENT ON COLUMN "lkp_payroll_impact_type"."affects_gross_pay" IS 'Whether this impact type modifies gross pay calculation';

COMMENT ON COLUMN "lkp_payroll_impact_type"."pay_percentage" IS 'Default pay percentage (100.00 = full pay, 0.00 = unpaid)';

COMMENT ON TABLE "lkp_approval_status" IS 'Generic approval workflow status (used across leave, comp, documents, etc.)';

COMMENT ON COLUMN "lkp_approval_status"."code" IS 'e.g. DRAFT, PENDING, APPROVED, REJECTED, CANCELLED, ESCALATED';

COMMENT ON COLUMN "lkp_approval_status"."is_approved_state" IS 'Whether this state represents approval';

COMMENT ON TABLE "lkp_leave_type" IS 'Classification of leave/absence (vacation, sick, FMLA, etc.)';

COMMENT ON COLUMN "lkp_leave_type"."code" IS 'e.g. VACATION, SICK, PERSONAL, FMLA, BEREAVEMENT, JURY_DUTY, MILITARY, PTO, STD, LTD';

COMMENT ON COLUMN "lkp_leave_type"."payroll_impact_type_id" IS 'FK → lkp_payroll_impact_type.id; default payroll treatment';

COMMENT ON COLUMN "lkp_leave_type"."is_accrued" IS 'Whether this leave type accrues a balance';

COMMENT ON COLUMN "lkp_leave_type"."is_protected" IS 'Whether legally protected (FMLA, ADA, military)';

COMMENT ON COLUMN "lkp_leave_type"."requires_documentation" IS 'Whether supporting docs are required';

COMMENT ON COLUMN "lkp_leave_type"."max_days_per_year" IS 'Statutory or policy cap, if applicable';

COMMENT ON TABLE "lkp_leave_status" IS 'Lifecycle status of a leave request';

COMMENT ON COLUMN "lkp_leave_status"."code" IS 'e.g. REQUESTED, APPROVED, IN_PROGRESS, COMPLETED, DENIED, CANCELLED';

COMMENT ON COLUMN "lkp_leave_status"."approval_status_id" IS 'FK → lkp_approval_status.id';

COMMENT ON COLUMN "lkp_leave_status"."is_on_leave" IS 'Whether this status means employee is actively on leave';

COMMENT ON TABLE "lkp_document_type" IS 'Classification of HR documents (offer letter, I-9, W-4, NDA, etc.)';

COMMENT ON COLUMN "lkp_document_type"."code" IS 'e.g. OFFER_LETTER, I9, W4, NDA, PERFORMANCE_REVIEW, POLICY_ACK, CONTRACT, CERTIFICATION, LICENSE';

COMMENT ON COLUMN "lkp_document_type"."requires_signature" IS 'Whether e-signature is required';

COMMENT ON COLUMN "lkp_document_type"."retention_days" IS 'Minimum retention period in days per policy/regulation';

COMMENT ON COLUMN "lkp_document_type"."is_employee_visible" IS 'Whether visible in employee self-service';

COMMENT ON TABLE "lkp_document_status" IS 'Lifecycle status of an HR document';

COMMENT ON COLUMN "lkp_document_status"."code" IS 'e.g. DRAFT, PENDING_SIGNATURE, SIGNED, EXPIRED, ARCHIVED, VOIDED, SUPERSEDED';

COMMENT ON COLUMN "lkp_document_status"."approval_status_id" IS 'FK → lkp_approval_status.id; mapped approval state if doc requires approval';

COMMENT ON COLUMN "lkp_document_status"."is_valid" IS 'Whether the document is considered legally valid in this state';

COMMENT ON TABLE "lkp_onboarding_plan_status" IS 'Status of an onboarding plan instance';

COMMENT ON COLUMN "lkp_onboarding_plan_status"."code" IS 'e.g. NOT_STARTED, IN_PROGRESS, BLOCKING_COMPLETE, COMPLETED, CANCELLED, ON_HOLD';

COMMENT ON TABLE "lkp_onboarding_task_type" IS 'Category of onboarding task (document, training, equipment, access, etc.)';

COMMENT ON COLUMN "lkp_onboarding_task_type"."code" IS 'e.g. DOCUMENT_SUBMISSION, TRAINING, EQUIPMENT_SETUP, SYSTEM_ACCESS, ORIENTATION, MENTOR_ASSIGNMENT, BENEFITS_ENROLLMENT, POLICY_ACK';

COMMENT ON COLUMN "lkp_onboarding_task_type"."document_type_id" IS 'FK → lkp_document_type.id; linked document type if this is a doc task';

COMMENT ON COLUMN "lkp_onboarding_task_type"."default_due_days" IS 'Default number of days after hire to complete';

COMMENT ON COLUMN "lkp_onboarding_task_type"."is_employee_action" IS 'Whether the new hire performs this task (vs HR/IT)';

COMMENT ON COLUMN "lkp_onboarding_task_type"."is_blocking" IS 'Whether this task blocks plan completion';

COMMENT ON TABLE "lkp_onboarding_task_status" IS 'Lifecycle status of an individual onboarding task';

COMMENT ON COLUMN "lkp_onboarding_task_status"."code" IS 'e.g. PENDING, IN_PROGRESS, COMPLETED, SKIPPED, OVERDUE, BLOCKED, WAIVED';

COMMENT ON COLUMN "lkp_onboarding_task_status"."approval_status_id" IS 'FK → lkp_approval_status.id; if task requires approval';

COMMENT ON COLUMN "lkp_onboarding_task_status"."is_complete_state" IS 'Whether this status counts toward plan completion';

COMMENT ON TABLE "lkp_org_unit_type" IS 'Type of organizational unit (legal entity, division, department, location, etc.)';

COMMENT ON COLUMN "lkp_org_unit_type"."code" IS 'e.g. LEGAL_ENTITY, COMPANY, DIVISION, DEPARTMENT, TEAM, COST_CENTER, BUSINESS_UNIT, LOCATION, REGION';

COMMENT ON COLUMN "lkp_org_unit_type"."allows_children" IS 'Whether this unit type can have child units';

COMMENT ON TABLE "lkp_org_status" IS 'Lifecycle status of an organizational unit';

COMMENT ON COLUMN "lkp_org_status"."code" IS 'e.g. ACTIVE, INACTIVE, PENDING_ACTIVATION, MERGED, DISSOLVED, ARCHIVED';

COMMENT ON COLUMN "lkp_org_status"."is_operational" IS 'Whether the org unit is operationally functional';

COMMENT ON TABLE "lkp_work_location_type" IS 'Classification of work locations (office, remote, hybrid, field, etc.)';

COMMENT ON COLUMN "lkp_work_location_type"."code" IS 'e.g. OFFICE, REMOTE, HYBRID, FIELD, CLIENT_SITE, WAREHOUSE';

COMMENT ON COLUMN "lkp_work_location_type"."is_on_site" IS 'Whether employees physically report to this location';

COMMENT ON COLUMN "lkp_work_location_type"."requires_address" IS 'Whether a physical address is required';

COMMENT ON TABLE "lkp_job_status" IS 'Status of a job definition/title in the catalog';

COMMENT ON COLUMN "lkp_job_status"."code" IS 'e.g. ACTIVE, FROZEN, ABOLISHED, UNDER_REVIEW, PENDING_APPROVAL, INACTIVE';

COMMENT ON COLUMN "lkp_job_status"."is_hirable" IS 'Whether positions under this job can be filled';

COMMENT ON TABLE "lkp_position_status" IS 'Status of an individual position (headcount slot)';

COMMENT ON COLUMN "lkp_position_status"."code" IS 'e.g. OPEN, FILLED, FROZEN, ABOLISHED, PENDING_BUDGET';

COMMENT ON COLUMN "lkp_position_status"."is_fillable" IS 'Whether this position can accept an incumbent';

COMMENT ON COLUMN "lkp_position_status"."is_occupied" IS 'Whether this status implies a current incumbent';
