-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-04-28T20:21:46.200Z

CREATE TABLE "lkp_result_class" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "sign_convention" varchar(10) NOT NULL,
  "affects_gross_pay" boolean NOT NULL DEFAULT false,
  "affects_net_pay" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_run_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "affects_accumulators" boolean NOT NULL DEFAULT true,
  "is_reportable" boolean NOT NULL DEFAULT true,
  "requires_base_run" boolean NOT NULL DEFAULT false,
  "generates_payments" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_run_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_editable" boolean NOT NULL DEFAULT false,
  "allows_calculation" boolean NOT NULL DEFAULT false,
  "allows_release" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sequence_order" int NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_result_set_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_scheduled" boolean NOT NULL DEFAULT false,
  "is_off_cycle" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_result_set_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_editable" boolean NOT NULL DEFAULT false,
  "is_released" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_employee_result_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_payable" boolean NOT NULL DEFAULT false,
  "is_reversible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_item_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "is_reversible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_payment_method" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_electronic" boolean NOT NULL DEFAULT false,
  "requires_bank_info" boolean NOT NULL DEFAULT false,
  "requires_physical_delivery" boolean NOT NULL DEFAULT false,
  "supports_split_payment" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_payment_context" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_scheduled" boolean NOT NULL DEFAULT false,
  "is_off_cycle" boolean NOT NULL DEFAULT false,
  "is_final" boolean NOT NULL DEFAULT false,
  "tax_method" varchar(30),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_check_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_negotiable" boolean NOT NULL DEFAULT false,
  "is_reissuable" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_impact_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "is_reversible" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_impact_source_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "result_class_id" integer,
  "is_system_generated" boolean NOT NULL DEFAULT true,
  "is_adjustable" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_posting_direction" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "multiplier" decimal(3,1),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_contribution_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_accumulator_family" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "result_class_id" integer,
  "is_tax_related" boolean NOT NULL DEFAULT false,
  "is_reportable" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_accumulator_scope_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "requires_participant" boolean NOT NULL DEFAULT false,
  "requires_employer" boolean NOT NULL DEFAULT false,
  "requires_jurisdiction" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_accumulator_balance_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_active_state" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_period_context" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "abbreviation" varchar(10) NOT NULL,
  "reset_frequency" varchar(20) NOT NULL,
  "reset_boundary" varchar(30),
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_scope_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_retroactive" boolean NOT NULL DEFAULT false,
  "requires_date_range" boolean NOT NULL DEFAULT false,
  "affects_prior_periods" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_scope_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_runnable" boolean NOT NULL DEFAULT false,
  "is_editable" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_population_method" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_dynamic" boolean NOT NULL DEFAULT false,
  "supports_preview" boolean NOT NULL DEFAULT true,
  "supports_override" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_funding_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_complete" boolean NOT NULL DEFAULT false,
  "allows_disbursement" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_remittance_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_transmitted" boolean NOT NULL DEFAULT false,
  "is_accepted" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "lkp_disbursement_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "label" varchar(100) NOT NULL,
  "description" text,
  "is_released" boolean NOT NULL DEFAULT false,
  "is_settled" boolean NOT NULL DEFAULT false,
  "is_error_state" boolean NOT NULL DEFAULT false,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

COMMENT ON TABLE "lkp_result_class" IS 'Top-level classification of payroll result lines (Earning, Deduction, Tax, Employer Contribution)';

COMMENT ON COLUMN "lkp_result_class"."code" IS 'e.g. EARNING, DEDUCTION, TAX, EMPLOYER_CONTRIBUTION';

COMMENT ON COLUMN "lkp_result_class"."sign_convention" IS 'POSITIVE (adds to gross) or NEGATIVE (subtracts from gross)';

COMMENT ON COLUMN "lkp_result_class"."affects_gross_pay" IS 'Whether this class factors into gross pay calculation';

COMMENT ON COLUMN "lkp_result_class"."affects_net_pay" IS 'Whether this class factors into net pay calculation';

COMMENT ON TABLE "lkp_run_type" IS 'Classification of payroll run types (regular, adjustment, correction, etc.)';

COMMENT ON COLUMN "lkp_run_type"."code" IS 'e.g. REGULAR, ADJUSTMENT, CORRECTION, REPROCESSING, SUPPLEMENTAL, SIMULATION';

COMMENT ON COLUMN "lkp_run_type"."affects_accumulators" IS 'Whether this run type updates accumulator balances';

COMMENT ON COLUMN "lkp_run_type"."is_reportable" IS 'Whether included in standard payroll reports and filings';

COMMENT ON COLUMN "lkp_run_type"."requires_base_run" IS 'Whether this type requires a reference to an original/base run';

COMMENT ON COLUMN "lkp_run_type"."generates_payments" IS 'Whether this run type produces disbursable payments';

COMMENT ON TABLE "lkp_run_status" IS 'Lifecycle status of a payroll run — governs what operations are permitted at each stage';

COMMENT ON COLUMN "lkp_run_status"."code" IS 'e.g. DRAFT, OPEN, CALCULATING, CALCULATED, UNDER_REVIEW, APPROVED, RELEASING, RELEASED, CLOSED, FAILED, CANCELLED';

COMMENT ON COLUMN "lkp_run_status"."is_editable" IS 'Whether payroll inputs can be modified in this state';

COMMENT ON COLUMN "lkp_run_status"."allows_calculation" IS 'Whether the calculation engine can execute';

COMMENT ON COLUMN "lkp_run_status"."allows_release" IS 'Whether payments can be released in this state';

COMMENT ON COLUMN "lkp_run_status"."is_error_state" IS 'Whether this state indicates a processing failure';

COMMENT ON COLUMN "lkp_run_status"."sequence_order" IS 'Expected progression order (1 = first state)';

COMMENT ON TABLE "lkp_result_set_type" IS 'Classification of result set origin (regular run, off-cycle, adjustment, correction)';

COMMENT ON COLUMN "lkp_result_set_type"."code" IS 'e.g. REGULAR_RUN, OFF_CYCLE, ADJUSTMENT_RUN, CORRECTION_RUN';

COMMENT ON COLUMN "lkp_result_set_type"."is_scheduled" IS 'Whether this type runs on a regular calendar schedule';

COMMENT ON COLUMN "lkp_result_set_type"."is_off_cycle" IS 'Whether this type represents an off-cycle / ad-hoc result set';

COMMENT ON TABLE "lkp_result_set_status" IS 'Lifecycle status of a payroll result set';

COMMENT ON COLUMN "lkp_result_set_status"."code" IS 'e.g. PENDING, CALCULATED, APPROVED, RELEASED, FINALIZED, ARCHIVED';

COMMENT ON COLUMN "lkp_result_set_status"."is_editable" IS 'Whether result set data can be modified';

COMMENT ON COLUMN "lkp_result_set_status"."is_released" IS 'Whether funds have been released for this result set';

COMMENT ON TABLE "lkp_employee_result_status" IS 'Lifecycle status of an individual employee payroll result';

COMMENT ON COLUMN "lkp_employee_result_status"."code" IS 'e.g. CALCULATED, APPROVED, RELEASED, FINALIZED, CORRECTED, REVERSED';

COMMENT ON COLUMN "lkp_employee_result_status"."is_payable" IS 'Whether payment can be issued in this state';

COMMENT ON COLUMN "lkp_employee_result_status"."is_reversible" IS 'Whether the result can be reversed from this state';

COMMENT ON TABLE "lkp_item_status" IS 'Status of a payroll line item (earning line, deduction line, tax line)';

COMMENT ON COLUMN "lkp_item_status"."code" IS 'e.g. DRAFT, POSTED, VOIDED, CORRECTED';

COMMENT ON COLUMN "lkp_item_status"."is_active_state" IS 'Whether the item is currently in effect';

COMMENT ON COLUMN "lkp_item_status"."is_reversible" IS 'Whether the item can be voided or corrected from this state';

COMMENT ON TABLE "lkp_payment_method" IS 'How payment is delivered to the employee (direct deposit, check, paycard, etc.)';

COMMENT ON COLUMN "lkp_payment_method"."code" IS 'e.g. DIRECT_DEPOSIT, PRINTED_CHECK, PAYCARD, CASH, MANUAL_CHECK, OTHER';

COMMENT ON COLUMN "lkp_payment_method"."is_electronic" IS 'Whether payment is transmitted electronically (ACH, wire, paycard)';

COMMENT ON COLUMN "lkp_payment_method"."requires_bank_info" IS 'Whether employee bank/routing info is required';

COMMENT ON COLUMN "lkp_payment_method"."requires_physical_delivery" IS 'Whether a physical instrument must be delivered';

COMMENT ON COLUMN "lkp_payment_method"."supports_split_payment" IS 'Whether this method supports split/partial allocation';

COMMENT ON TABLE "lkp_payment_context" IS 'Context in which a payment is issued — affects tax withholding method and reporting';

COMMENT ON COLUMN "lkp_payment_context"."code" IS 'e.g. REGULAR, SUPPLEMENTAL, CORRECTION, FINAL_PAY, OFF_CYCLE';

COMMENT ON COLUMN "lkp_payment_context"."is_scheduled" IS 'Whether this context occurs on the regular pay calendar';

COMMENT ON COLUMN "lkp_payment_context"."is_off_cycle" IS 'Whether this is an off-cycle payment';

COMMENT ON COLUMN "lkp_payment_context"."is_final" IS 'Whether this context represents final/separation pay';

COMMENT ON COLUMN "lkp_payment_context"."tax_method" IS 'Default tax calculation method: AGGREGATE, FLAT_RATE, SUPPLEMENTAL_RATE';

COMMENT ON TABLE "lkp_check_status" IS 'Lifecycle status of a payroll check or payment instrument';

COMMENT ON COLUMN "lkp_check_status"."code" IS 'e.g. DRAFT, GENERATED, RELEASED, VOIDED, REPLACED, RETURNED';

COMMENT ON COLUMN "lkp_check_status"."is_negotiable" IS 'Whether the check can be cashed/deposited in this state';

COMMENT ON COLUMN "lkp_check_status"."is_reissuable" IS 'Whether a replacement can be issued from this state';

COMMENT ON TABLE "lkp_impact_status" IS 'Status of a payroll impact record';

COMMENT ON COLUMN "lkp_impact_status"."code" IS 'e.g. CALCULATED, POSTED, REVERSED, CORRECTED, SUPERSEDED';

COMMENT ON COLUMN "lkp_impact_status"."is_active_state" IS 'Whether the impact is currently reflected in balances';

COMMENT ON COLUMN "lkp_impact_status"."is_reversible" IS 'Whether the impact can be reversed from this state';

COMMENT ON TABLE "lkp_impact_source_type" IS 'Identifies where a payroll impact originated (earnings line, deduction line, tax line, etc.)';

COMMENT ON COLUMN "lkp_impact_source_type"."code" IS 'e.g. EARNINGS_LINE, DEDUCTION_LINE, TAX_LINE, EMPLOYER_CONTRIBUTION_LINE, CORRECTION_LINE, MANUAL_ADJUSTMENT, OTHER';

COMMENT ON COLUMN "lkp_impact_source_type"."result_class_id" IS 'FK → lkp_result_class.id; NULL for CORRECTION_LINE, MANUAL_ADJUSTMENT, OTHER';

COMMENT ON COLUMN "lkp_impact_source_type"."is_system_generated" IS 'Whether this source type is created by the calc engine vs manual entry';

COMMENT ON COLUMN "lkp_impact_source_type"."is_adjustable" IS 'Whether manual adjustments are allowed for this source type';

COMMENT ON TABLE "lkp_posting_direction" IS 'Direction of a posting or accumulator contribution (increase, decrease, neutral, derived)';

COMMENT ON COLUMN "lkp_posting_direction"."code" IS 'e.g. INCREASE, DECREASE, NEUTRAL, DERIVED';

COMMENT ON COLUMN "lkp_posting_direction"."multiplier" IS '+1.0 (INCREASE), -1.0 (DECREASE), 0.0 (NEUTRAL), NULL (DERIVED — computed at runtime)';

COMMENT ON TABLE "lkp_contribution_type" IS 'Nature of an accumulator contribution (standard posting, reversal, correction, reset)';

COMMENT ON COLUMN "lkp_contribution_type"."code" IS 'e.g. STANDARD, REVERSAL, CORRECTION, RESET';

COMMENT ON TABLE "lkp_accumulator_family" IS 'Functional grouping of accumulators (gross wages, deductions, taxes, etc.)';

COMMENT ON COLUMN "lkp_accumulator_family"."code" IS 'e.g. GROSS_WAGES, PRE_TAX_DEDUCTIONS, FEDERAL_TAX_WITHHELD, SOCIAL_SECURITY, MEDICARE, RETIREMENT';

COMMENT ON COLUMN "lkp_accumulator_family"."result_class_id" IS 'FK → lkp_result_class.id; primary result class for this family';

COMMENT ON COLUMN "lkp_accumulator_family"."is_tax_related" IS 'Whether this family relates to tax accumulators';

COMMENT ON COLUMN "lkp_accumulator_family"."is_reportable" IS 'Whether included in standard year-end reporting';

COMMENT ON TABLE "lkp_accumulator_scope_type" IS 'Dimensional scope of an accumulator (employee-level, employer-level, jurisdiction-level)';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."code" IS 'e.g. EMPLOYEE, EMPLOYER, EMPLOYEE_JURISDICTION, EMPLOYER_JURISDICTION, CLIENT_JURISDICTION';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."requires_participant" IS 'Whether a participant (employee) ID is required';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."requires_employer" IS 'Whether an employer ID is required';

COMMENT ON COLUMN "lkp_accumulator_scope_type"."requires_jurisdiction" IS 'Whether a jurisdiction ID is required';

COMMENT ON TABLE "lkp_accumulator_balance_status" IS 'Status of an accumulator balance snapshot (active, reset at period boundary, archived)';

COMMENT ON COLUMN "lkp_accumulator_balance_status"."code" IS 'e.g. ACTIVE, RESET, ARCHIVED';

COMMENT ON COLUMN "lkp_accumulator_balance_status"."is_active_state" IS 'Whether the balance is currently in use';

COMMENT ON TABLE "lkp_period_context" IS 'Time window for accumulator balances — period-to-date, quarter-to-date, year-to-date, lifetime';

COMMENT ON COLUMN "lkp_period_context"."code" IS 'e.g. PTD, QTD, YTD, PLAN_YEAR, LTD';

COMMENT ON COLUMN "lkp_period_context"."abbreviation" IS 'Short display code: PTD, QTD, YTD, PY, LTD';

COMMENT ON COLUMN "lkp_period_context"."reset_frequency" IS 'When the accumulator resets: PER_PAY, QUARTERLY, ANNUALLY, PLAN_YEAR, NEVER';

COMMENT ON COLUMN "lkp_period_context"."reset_boundary" IS 'Boundary event: PAY_PERIOD_END, QUARTER_END, YEAR_END, PLAN_YEAR_END, NULL';

COMMENT ON TABLE "lkp_scope_type" IS 'Scope of a payroll calculation — full run, catch-up, retroactive, recovery';

COMMENT ON COLUMN "lkp_scope_type"."code" IS 'e.g. FULL, CATCH_UP, RETRO, RECOVERY';

COMMENT ON COLUMN "lkp_scope_type"."is_retroactive" IS 'Whether this scope reaches back to prior periods';

COMMENT ON COLUMN "lkp_scope_type"."requires_date_range" IS 'Whether a lookback date range is required';

COMMENT ON COLUMN "lkp_scope_type"."affects_prior_periods" IS 'Whether accumulator adjustments are applied to prior periods';

COMMENT ON TABLE "lkp_scope_status" IS 'Lifecycle status of a processing scope or batch';

COMMENT ON COLUMN "lkp_scope_status"."code" IS 'e.g. DRAFT, VALIDATED, READY, RUNNING, COMPLETED, FAILED, CANCELLED';

COMMENT ON COLUMN "lkp_scope_status"."is_runnable" IS 'Whether the scope/batch can be submitted for processing';

COMMENT ON COLUMN "lkp_scope_status"."is_editable" IS 'Whether scope parameters can be modified';

COMMENT ON COLUMN "lkp_scope_status"."is_error_state" IS 'Whether this state indicates a processing failure';

COMMENT ON TABLE "lkp_population_method" IS 'How the employee population for a payroll run is determined (explicit list, dynamic query, exception-based)';

COMMENT ON COLUMN "lkp_population_method"."code" IS 'e.g. EXPLICIT, QUERY, EXCEPTION';

COMMENT ON COLUMN "lkp_population_method"."is_dynamic" IS 'Whether population is evaluated at runtime (QUERY) vs fixed at setup (EXPLICIT)';

COMMENT ON COLUMN "lkp_population_method"."supports_preview" IS 'Whether the resolved population can be previewed before run';

COMMENT ON COLUMN "lkp_population_method"."supports_override" IS 'Whether individual members can be added/removed after resolution';

COMMENT ON TABLE "lkp_funding_status" IS 'Whether payroll funding (employer bank draw) succeeded, partially succeeded, or failed';

COMMENT ON COLUMN "lkp_funding_status"."code" IS 'e.g. FUNDED, PARTIALLY_FUNDED, FAILED';

COMMENT ON COLUMN "lkp_funding_status"."is_complete" IS 'Whether funding is fully satisfied';

COMMENT ON COLUMN "lkp_funding_status"."allows_disbursement" IS 'Whether disbursement can proceed in this state';

COMMENT ON COLUMN "lkp_funding_status"."is_error_state" IS 'Whether this state indicates a funding failure';

COMMENT ON TABLE "lkp_remittance_status" IS 'Status of a tax or benefit remittance to an agency or vendor';

COMMENT ON COLUMN "lkp_remittance_status"."code" IS 'e.g. PREPARED, RELEASED, TRANSMITTED, ACCEPTED, REJECTED';

COMMENT ON COLUMN "lkp_remittance_status"."is_transmitted" IS 'Whether the remittance has been sent to the receiving party';

COMMENT ON COLUMN "lkp_remittance_status"."is_accepted" IS 'Whether the receiving party has acknowledged receipt';

COMMENT ON COLUMN "lkp_remittance_status"."is_error_state" IS 'Whether this state indicates a remittance failure';

COMMENT ON TABLE "lkp_disbursement_status" IS 'Status of an employee payment disbursement through the banking settlement lifecycle';

COMMENT ON COLUMN "lkp_disbursement_status"."code" IS 'e.g. PREPARED, RELEASED, SETTLED, RETURNED';

COMMENT ON COLUMN "lkp_disbursement_status"."is_released" IS 'Whether funds have been released for transfer';

COMMENT ON COLUMN "lkp_disbursement_status"."is_settled" IS 'Whether the transfer has fully settled';

COMMENT ON COLUMN "lkp_disbursement_status"."is_error_state" IS 'Whether this state indicates a disbursement failure';
