-- ============================================================
-- HCM Platform — Tax Calculation Pipeline Schema
-- Version: v0.2
-- Status: Draft
-- Generated from: schemas/dbml/hcm_tax_pipeline.dbml
-- Covers: Tax jurisdiction registry, calculation step pipeline,
--         effective-dated rate tables (brackets, flat rates,
--         tiered brackets, allowances, credits),
--         employee withholding form submissions,
--         consolidated form detail table (all form families),
--         form field definition registry,
--         configuration audit log
-- Note: No FK constraints applied — references documented in
--       column comments. Column names are consistent to support
--       FK addition without renaming.
-- ============================================================

-- ============================================================
-- TAX CONFIGURATION
-- ============================================================

CREATE TABLE "tax_jurisdiction" (
  "jurisdiction_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jurisdiction_code" varchar(20)  UNIQUE NOT NULL,
  "jurisdiction_name" varchar(100) NOT NULL,
  "country_code"      char(2)      NOT NULL,
  "is_active"         boolean      NOT NULL DEFAULT true
);

CREATE TABLE "payroll_calculation_steps" (
  "step_id"                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jurisdiction_id"          integer      NOT NULL,
  "step_code"                varchar(50)  UNIQUE NOT NULL,
  "step_name"                varchar(100) NOT NULL,
  "step_type"                varchar(30)  NOT NULL,
  "calculation_category"     varchar(40)  NOT NULL,
  "sequence_number"          integer      NOT NULL,
  "applies_to"               varchar(10)  NOT NULL,
  "reduces_income_tax_wages" boolean      NOT NULL DEFAULT false,
  "reduces_fica_wages"       boolean      NOT NULL DEFAULT false,
  "status_code"              varchar(30)  NOT NULL DEFAULT 'DRAFT',
  "is_active"                boolean      NOT NULL DEFAULT true,
  CONSTRAINT "chk_step_type" CHECK ("step_type" IN (
      'STANDARD_DEDUCTION', 'ALLOWANCE', 'PROGRESSIVE_BRACKET',
      'CREDIT', 'FLAT_RATE', 'TIERED_FLAT', 'PERCENTAGE_OF_PRIOR')),
  CONSTRAINT "chk_applies_to" CHECK ("applies_to" IN ('EMPLOYEE', 'EMPLOYER', 'BOTH')),
  CONSTRAINT "chk_step_status" CHECK ("status_code" IN (
      'DRAFT', 'PENDING_REVIEW', 'APPROVED', 'ACTIVE', 'ARCHIVED'))
);

CREATE TABLE "tax_filing_status" (
  "filing_status_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jurisdiction_id"    integer     NOT NULL,
  "filing_status_code" varchar(20) NOT NULL,
  "filing_status_name" varchar(50) NOT NULL
);

-- ============================================================
-- TAX RATE TABLES
-- ============================================================

CREATE TABLE "tax_brackets" (
  "bracket_id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_code"          varchar(50)   NOT NULL,
  "filing_status_code" varchar(20)   NULL,
  "effective_from"     date          NOT NULL,
  "effective_to"       date          NULL,
  "lower_limit"        decimal(18,4) NOT NULL,
  "upper_limit"        decimal(18,4) NULL,
  "rate"               decimal(10,6) NOT NULL
);

CREATE TABLE "tax_flat_rates" (
  "flat_rate_id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_code"            varchar(50)   NOT NULL,
  "effective_from"       date          NOT NULL,
  "effective_to"         date          NULL,
  "rate"                 decimal(10,6) NOT NULL,
  "wage_base"            decimal(18,4) NULL,
  "period_cap_amount"    decimal(18,4) NULL,
  "annual_cap_amount"    decimal(18,4) NULL,
  "depends_on_step_code" varchar(50)   NULL
);

CREATE TABLE "tax_tiered_brackets" (
  "tiered_bracket_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_code"         varchar(50)   NOT NULL,
  "effective_from"    date          NOT NULL,
  "effective_to"      date          NULL,
  "lower_limit"       decimal(18,4) NOT NULL,
  "upper_limit"       decimal(18,4) NULL,
  "rate"              decimal(10,6) NOT NULL,
  "period_cap_amount" decimal(18,4) NULL,
  "annual_cap_amount" decimal(18,4) NULL
);

CREATE TABLE "tax_allowances" (
  "allowance_id"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_code"          varchar(50)   NOT NULL,
  "filing_status_code" varchar(20)   NULL,
  "effective_from"     date          NOT NULL,
  "effective_to"       date          NULL,
  "annual_amount"      decimal(18,4) NOT NULL
);

CREATE TABLE "tax_credits" (
  "credit_id"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "step_code"      varchar(50)   NOT NULL,
  "effective_from" date          NOT NULL,
  "effective_to"   date          NULL,
  "annual_amount"  decimal(18,4) NOT NULL,
  "credit_rate"    decimal(10,6) NOT NULL,
  "is_refundable"  boolean       NOT NULL DEFAULT false
);

-- ============================================================
-- EMPLOYEE TAX FORMS
-- ============================================================

CREATE TABLE "lkp_tax_form_type" (
  "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "employee_tax_form_submission" (
  "submission_id"      uuid         PRIMARY KEY NOT NULL,
  "employment_id"      uuid         NOT NULL,
  "jurisdiction_id"    integer      NOT NULL,
  "form_type_id"       integer      NOT NULL,
  "source_document_id" uuid         NULL,
  "submitted_date"     date         NOT NULL,
  "exempt_flag"        boolean      NOT NULL DEFAULT false,
  "effective_from"     date         NOT NULL,
  "effective_to"       date         NULL,
  "created_by"         varchar(100) NOT NULL,
  "creation_timestamp" timestamptz  NOT NULL
);

CREATE TABLE "employee_tax_form_detail" (
  "submission_id"          uuid          PRIMARY KEY NOT NULL,
  "filing_status_code"     varchar(20)   NULL,
  "allowance_count"        integer       NOT NULL DEFAULT 0,
  "additional_withholding" numeric(18,4) NOT NULL DEFAULT 0,
  "is_legacy_form"         boolean       NOT NULL DEFAULT false,
  "other_income_amount"    numeric(18,4) NOT NULL DEFAULT 0,
  "deductions_amount"      numeric(18,4) NOT NULL DEFAULT 0,
  "credits_amount"         numeric(18,4) NOT NULL DEFAULT 0,
  "claim_code"             smallint      NULL,
  "total_claim_amount"     numeric(18,4) NULL,
  "additional_tax_amount"  numeric(18,4) NOT NULL DEFAULT 0
);

-- ============================================================
-- FORM FIELD DEFINITION
-- ============================================================

CREATE TABLE "form_field_definition" (
  "field_definition_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_type_code"        varchar(20)  NOT NULL,
  "effective_from"        date         NOT NULL,
  "effective_to"          date         NULL,
  "field_key"             varchar(80)  NOT NULL,
  "display_label"         varchar(200) NOT NULL,
  "field_type"            varchar(40)  NOT NULL,
  "section_key"           varchar(80)  NULL,
  "section_label"         varchar(160) NULL,
  "display_order"         integer      NOT NULL,
  "is_required"           boolean      NOT NULL DEFAULT false,
  "detail_column_name"    varchar(80)  NULL,
  "promotes_to_column"    varchar(80)  NULL,
  "validation_rules_json" text         NULL,
  "visibility_rule_json"  text         NULL,
  "enum_values_json"      text         NULL,
  "default_value_text"    varchar(200) NULL,
  "help_text"             text         NULL,
  "status_code"           varchar(30)  NOT NULL DEFAULT 'DRAFT',
  "is_active"             boolean      NOT NULL DEFAULT true,
  CONSTRAINT "uq_form_field_eff" UNIQUE ("form_type_code", "field_key", "effective_from"),
  CONSTRAINT "chk_field_type" CHECK ("field_type" IN (
      'TEXT', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'ENUM', 'DATE')),
  CONSTRAINT "chk_field_status" CHECK ("status_code" IN (
      'DRAFT', 'PENDING_REVIEW', 'APPROVED', 'ACTIVE', 'ARCHIVED'))
);

-- ============================================================
-- CONFIGURATION AUDIT LOG
-- ============================================================

CREATE TABLE "configuration_audit_log" (
  "audit_log_id"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entity_name"       varchar(80)  NOT NULL,
  "entity_id_text"    varchar(200) NOT NULL,
  "action_code"       varchar(40)  NOT NULL,
  "prior_status_code" varchar(30)  NULL,
  "new_status_code"   varchar(30)  NULL,
  "changed_by"        varchar(100) NOT NULL,
  "changed_at"        timestamp    NOT NULL,
  "approval_note"     text         NULL,
  "snapshot_json"     text         NULL,
  CONSTRAINT "chk_action_code" CHECK ("action_code" IN (
      'CREATED', 'SUBMITTED_FOR_REVIEW', 'APPROVED', 'ACTIVATED',
      'ARCHIVED', 'REJECTED', 'EDITED'))
);

-- ============================================================
-- INDEXES — TAX CONFIGURATION
-- ============================================================

CREATE UNIQUE INDEX ON "tax_jurisdiction" ("jurisdiction_code");

CREATE INDEX ON "tax_jurisdiction" ("country_code");

CREATE INDEX ON "tax_jurisdiction" ("is_active");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id");

CREATE UNIQUE INDEX ON "payroll_calculation_steps" ("step_code");

CREATE INDEX ON "payroll_calculation_steps" ("step_type");

CREATE INDEX ON "payroll_calculation_steps" ("calculation_category");

CREATE INDEX ON "payroll_calculation_steps" ("status_code");

CREATE INDEX ON "payroll_calculation_steps" ("is_active");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id", "sequence_number");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id", "is_active");

CREATE INDEX ON "payroll_calculation_steps" ("jurisdiction_id", "status_code");

CREATE INDEX ON "tax_filing_status" ("jurisdiction_id");

CREATE UNIQUE INDEX ON "tax_filing_status" ("jurisdiction_id", "filing_status_code");

-- ============================================================
-- INDEXES — TAX RATE TABLES
-- ============================================================

CREATE INDEX ON "tax_brackets" ("step_code");

CREATE INDEX ON "tax_brackets" ("step_code", "filing_status_code", "effective_from");

CREATE INDEX ON "tax_brackets" ("effective_from");

CREATE INDEX ON "tax_flat_rates" ("step_code");

CREATE INDEX ON "tax_flat_rates" ("step_code", "effective_from");

CREATE INDEX ON "tax_flat_rates" ("effective_from");

CREATE INDEX ON "tax_tiered_brackets" ("step_code");

CREATE INDEX ON "tax_tiered_brackets" ("step_code", "effective_from");

CREATE INDEX ON "tax_tiered_brackets" ("effective_from");

CREATE INDEX ON "tax_allowances" ("step_code");

CREATE INDEX ON "tax_allowances" ("step_code", "filing_status_code", "effective_from");

CREATE INDEX ON "tax_allowances" ("effective_from");

CREATE INDEX ON "tax_credits" ("step_code");

CREATE INDEX ON "tax_credits" ("step_code", "effective_from");

CREATE INDEX ON "tax_credits" ("effective_from");

-- ============================================================
-- INDEXES — EMPLOYEE TAX FORMS
-- ============================================================

CREATE UNIQUE INDEX ON "lkp_tax_form_type" ("code");

CREATE INDEX ON "employee_tax_form_submission" ("employment_id");

CREATE INDEX ON "employee_tax_form_submission" ("jurisdiction_id");

CREATE INDEX ON "employee_tax_form_submission" ("form_type_id");

CREATE INDEX ON "employee_tax_form_submission" ("effective_from");

CREATE INDEX ON "employee_tax_form_submission" ("employment_id", "jurisdiction_id", "effective_from");

CREATE INDEX ON "employee_tax_form_submission" ("employment_id", "jurisdiction_id", "effective_to");

-- ============================================================
-- COLUMN COMMENTS — tax_jurisdiction
-- ============================================================

COMMENT ON COLUMN "tax_jurisdiction"."jurisdiction_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_jurisdiction"."jurisdiction_code"
  IS 'e.g. US-FED, US-NY, CA-FED, BB';

COMMENT ON COLUMN "tax_jurisdiction"."country_code"
  IS 'ISO 3166-1 alpha-2';

-- ============================================================
-- COLUMN COMMENTS — payroll_calculation_steps
-- ============================================================

COMMENT ON COLUMN "payroll_calculation_steps"."step_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "payroll_calculation_steps"."jurisdiction_id"
  IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "payroll_calculation_steps"."step_code"
  IS 'e.g. US_FED_INCOME_TAX, BB_NIS. Used as StepCode in ICalculationStep.';

COMMENT ON COLUMN "payroll_calculation_steps"."step_type"
  IS 'STANDARD_DEDUCTION | ALLOWANCE | PROGRESSIVE_BRACKET | CREDIT | FLAT_RATE | TIERED_FLAT | PERCENTAGE_OF_PRIOR';

COMMENT ON COLUMN "payroll_calculation_steps"."calculation_category"
  IS 'PRETAX_BENEFIT | DEDUCTION_ALLOWANCE | INCOME_TAX | CREDIT | SOCIAL_INSURANCE | SUBNATIONAL_TAX | DERIVED_TAX | POSTTAX | EMPLOYER_CONTRIBUTION. Controls wage base selection in FlatRateStep/TieredFlatStep.';

COMMENT ON COLUMN "payroll_calculation_steps"."sequence_number"
  IS 'Execution order within pipeline: 100–199 pre-tax benefits, 200–299 deductions/allowances, 300–399 national income tax, 400–499 credits, 500–599 social insurance, 600–699 sub-national income tax, 700–799 derived taxes, 800–899 post-tax deductions, 900–999 employer contributions';

COMMENT ON COLUMN "payroll_calculation_steps"."applies_to"
  IS 'EMPLOYEE | EMPLOYER | BOTH';

COMMENT ON COLUMN "payroll_calculation_steps"."reduces_income_tax_wages"
  IS 'TRUE for pre-tax steps that reduce IncomeTaxableWages (e.g. traditional 401k, health FSA).';

COMMENT ON COLUMN "payroll_calculation_steps"."reduces_fica_wages"
  IS 'TRUE for pre-tax steps that also reduce FicaTaxableWages (e.g. Section 125 health premiums). Both flags may be TRUE.';

COMMENT ON COLUMN "payroll_calculation_steps"."status_code"
  IS 'DRAFT | PENDING_REVIEW | APPROVED | ACTIVE | ARCHIVED. New steps start as DRAFT; must reach ACTIVE before inclusion in live pipeline queries.';

-- ============================================================
-- COLUMN COMMENTS — tax_filing_status
-- ============================================================

COMMENT ON COLUMN "tax_filing_status"."filing_status_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_filing_status"."jurisdiction_id"
  IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "tax_filing_status"."filing_status_code"
  IS 'e.g. SINGLE, MFJ, MFS, HOH';

-- ============================================================
-- COLUMN COMMENTS — tax_brackets
-- ============================================================

COMMENT ON COLUMN "tax_brackets"."bracket_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_brackets"."step_code"
  IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_brackets"."filing_status_code"
  IS 'NULL = applies to all filing statuses for this step';

COMMENT ON COLUMN "tax_brackets"."effective_to"
  IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_brackets"."lower_limit"
  IS 'Annual income lower bound (inclusive)';

COMMENT ON COLUMN "tax_brackets"."upper_limit"
  IS 'NULL = no upper limit (top bracket)';

COMMENT ON COLUMN "tax_brackets"."rate"
  IS 'Marginal rate e.g. 0.220000 = 22%';

-- ============================================================
-- COLUMN COMMENTS — tax_flat_rates
-- ============================================================

COMMENT ON COLUMN "tax_flat_rates"."flat_rate_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_flat_rates"."step_code"
  IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_flat_rates"."effective_to"
  IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_flat_rates"."rate"
  IS 'e.g. 0.062000 = 6.2%';

COMMENT ON COLUMN "tax_flat_rates"."wage_base"
  IS 'Annual wage ceiling; NULL = no cap on taxable base';

COMMENT ON COLUMN "tax_flat_rates"."period_cap_amount"
  IS 'Maximum deduction per pay period';

COMMENT ON COLUMN "tax_flat_rates"."annual_cap_amount"
  IS 'Maximum deduction per calendar year; enforced via YTD accumulator';

COMMENT ON COLUMN "tax_flat_rates"."depends_on_step_code"
  IS 'PERCENTAGE_OF_PRIOR only — step whose result this rate is applied to';

-- ============================================================
-- COLUMN COMMENTS — tax_tiered_brackets
-- ============================================================

COMMENT ON COLUMN "tax_tiered_brackets"."tiered_bracket_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_tiered_brackets"."step_code"
  IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_tiered_brackets"."effective_to"
  IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_tiered_brackets"."lower_limit"
  IS 'Annual earnings lower bound for this tier';

COMMENT ON COLUMN "tax_tiered_brackets"."upper_limit"
  IS 'NULL = no upper limit';

COMMENT ON COLUMN "tax_tiered_brackets"."period_cap_amount"
  IS 'Per-period contribution cap within this tier';

COMMENT ON COLUMN "tax_tiered_brackets"."annual_cap_amount"
  IS 'Annual contribution cap within this tier; enforced via YTD accumulator';

-- ============================================================
-- COLUMN COMMENTS — tax_allowances
-- ============================================================

COMMENT ON COLUMN "tax_allowances"."allowance_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_allowances"."step_code"
  IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_allowances"."filing_status_code"
  IS 'NULL = applies to all filing statuses';

COMMENT ON COLUMN "tax_allowances"."effective_to"
  IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_allowances"."annual_amount"
  IS 'Annual deduction amount; divided by PayPeriodsPerYear at runtime';

-- ============================================================
-- COLUMN COMMENTS — tax_credits
-- ============================================================

COMMENT ON COLUMN "tax_credits"."credit_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "tax_credits"."step_code"
  IS 'FK → payroll_calculation_steps.step_code';

COMMENT ON COLUMN "tax_credits"."effective_to"
  IS 'NULL = currently effective';

COMMENT ON COLUMN "tax_credits"."annual_amount"
  IS 'Gross credit base e.g. Canada BPA CAD 16,129';

COMMENT ON COLUMN "tax_credits"."credit_rate"
  IS 'Rate applied to annual_amount e.g. 0.150000 = 15% for Canada BPA';

-- ============================================================
-- COLUMN COMMENTS — lkp_tax_form_type
-- ============================================================

COMMENT ON COLUMN "lkp_tax_form_type"."id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "lkp_tax_form_type"."code"
  IS 'Managed by ILookupCache. Values: W4_2020, W4_LEGACY, IT_2104, DE_4, G_4, TD1, TD1X, BB_TD4';

-- ============================================================
-- COLUMN COMMENTS — employee_tax_form_submission
-- ============================================================

COMMENT ON COLUMN "employee_tax_form_submission"."submission_id"
  IS 'System-generated.';

COMMENT ON COLUMN "employee_tax_form_submission"."employment_id"
  IS 'FK → employment.employment_id';

COMMENT ON COLUMN "employee_tax_form_submission"."jurisdiction_id"
  IS 'FK → tax_jurisdiction.jurisdiction_id';

COMMENT ON COLUMN "employee_tax_form_submission"."form_type_id"
  IS 'FK → lkp_tax_form_type.id';

COMMENT ON COLUMN "employee_tax_form_submission"."source_document_id"
  IS 'FK → HRIS document store; nullable until scan attached';

COMMENT ON COLUMN "employee_tax_form_submission"."submitted_date"
  IS 'Date employee signed and submitted the form';

COMMENT ON COLUMN "employee_tax_form_submission"."exempt_flag"
  IS 'Employee claimed withholding exemption on the form';

COMMENT ON COLUMN "employee_tax_form_submission"."effective_to"
  IS 'NULL = currently active; set when superseded by a new filing';

-- ============================================================
-- COLUMN COMMENTS — employee_tax_form_detail
-- ============================================================

COMMENT ON COLUMN "employee_tax_form_detail"."submission_id"
  IS 'FK → employee_tax_form_submission.submission_id';

COMMENT ON COLUMN "employee_tax_form_detail"."filing_status_code"
  IS 'W-4 Step 1c, IT-2104 filing status, etc. NULL for TD1/TD1X.';

COMMENT ON COLUMN "employee_tax_form_detail"."allowance_count"
  IS 'W-4 legacy Step 5, or state allowance count. 0 for W-4 2020+ and TD1.';

COMMENT ON COLUMN "employee_tax_form_detail"."additional_withholding"
  IS 'W-4 Step 4c / state extra withholding per period. 0 for TD1.';

COMMENT ON COLUMN "employee_tax_form_detail"."is_legacy_form"
  IS 'TRUE = pre-2020 W-4 (allowances format). FALSE for all other form types.';

COMMENT ON COLUMN "employee_tax_form_detail"."other_income_amount"
  IS 'W-4 2020+ Step 4a — added to annualized IncomeTaxableWages before bracket walk. 0 for all other forms.';

COMMENT ON COLUMN "employee_tax_form_detail"."deductions_amount"
  IS 'W-4 2020+ Step 4b — subtracted from annualized IncomeTaxableWages before bracket walk. 0 for all other forms.';

COMMENT ON COLUMN "employee_tax_form_detail"."credits_amount"
  IS 'W-4 2020+ Step 3 — subtracted from annual tax after bracket walk. 0 for all other forms.';

COMMENT ON COLUMN "employee_tax_form_detail"."claim_code"
  IS 'TD1/TD1X/BB-TD4: CRA standard claim code 1–10. NULL for all other forms and when total_claim_amount is provided.';

COMMENT ON COLUMN "employee_tax_form_detail"."total_claim_amount"
  IS 'TD1/TD1X/BB-TD4: custom worksheet total. NULL for all other forms and when claim_code is provided.';

COMMENT ON COLUMN "employee_tax_form_detail"."additional_tax_amount"
  IS 'TD1/TD1X/BB-TD4: additional tax to deduct per period. 0 for all other forms.';

COMMENT ON TABLE "employee_tax_form_detail"
  IS 'Consolidated detail table for all Phase 5 form families. TD1 XOR rule (exactly one of claim_code / total_claim_amount non-null) is enforced by the save service, not a DB constraint.';

-- ============================================================
-- COLUMN COMMENTS — form_field_definition
-- ============================================================

COMMENT ON COLUMN "form_field_definition"."field_definition_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "form_field_definition"."form_type_code"
  IS 'FK → lkp_tax_form_type.code';

COMMENT ON COLUMN "form_field_definition"."effective_to"
  IS 'NULL = currently effective';

COMMENT ON COLUMN "form_field_definition"."field_key"
  IS 'Stable identifier for this field within the form type';

COMMENT ON COLUMN "form_field_definition"."field_type"
  IS 'TEXT | INTEGER | DECIMAL | BOOLEAN | ENUM | DATE';

COMMENT ON COLUMN "form_field_definition"."detail_column_name"
  IS 'Physical column in employee_tax_form_detail that stores this field''s value';

COMMENT ON COLUMN "form_field_definition"."promotes_to_column"
  IS 'CalculationContext property that receives this value at pipeline load time';

COMMENT ON COLUMN "form_field_definition"."validation_rules_json"
  IS 'ANSI TEXT — structured validation rule (min, max, regex, etc.)';

COMMENT ON COLUMN "form_field_definition"."visibility_rule_json"
  IS 'ANSI TEXT — conditional display rule for form renderer';

COMMENT ON COLUMN "form_field_definition"."enum_values_json"
  IS 'ANSI TEXT — allowed values for ENUM field_type';

COMMENT ON COLUMN "form_field_definition"."status_code"
  IS 'DRAFT | PENDING_REVIEW | APPROVED | ACTIVE | ARCHIVED';

-- ============================================================
-- INDEXES — form_field_definition
-- ============================================================

CREATE INDEX ON "form_field_definition" ("form_type_code");

CREATE INDEX ON "form_field_definition" ("effective_from");

CREATE INDEX ON "form_field_definition" ("status_code");

CREATE INDEX ON "form_field_definition" ("is_active");

-- ============================================================
-- COLUMN COMMENTS — configuration_audit_log
-- ============================================================

COMMENT ON COLUMN "configuration_audit_log"."audit_log_id"
  IS 'Auto-generated.';

COMMENT ON COLUMN "configuration_audit_log"."entity_name"
  IS 'Table name, e.g. payroll_calculation_steps, form_field_definition';

COMMENT ON COLUMN "configuration_audit_log"."entity_id_text"
  IS 'String representation of entity PK (step_code, field_definition_id, etc.)';

COMMENT ON COLUMN "configuration_audit_log"."action_code"
  IS 'CREATED | SUBMITTED_FOR_REVIEW | APPROVED | ACTIVATED | ARCHIVED | REJECTED | EDITED';

COMMENT ON COLUMN "configuration_audit_log"."snapshot_json"
  IS 'Full row state at transition time; ANSI TEXT for portability';

COMMENT ON TABLE "configuration_audit_log"
  IS 'Append-only. Never updated or deleted — source of truth for compliance review.';

-- ============================================================
-- INDEXES — configuration_audit_log
-- ============================================================

CREATE INDEX ON "configuration_audit_log" ("entity_name");

CREATE INDEX ON "configuration_audit_log" ("entity_name", "entity_id_text");

CREATE INDEX ON "configuration_audit_log" ("changed_at");

CREATE INDEX ON "configuration_audit_log" ("action_code");
